pipelines:
  default:
    - parallel:
      - step:
         name: Sync GitHub Mirror
         image: alpine/git:latest
         clone:
          enabled: false
         script:
          - git clone --bare git@bitbucket.org:wiazard34/java-tools.git
          - cd java-tools.git
          - git push --mirror git@github.com:aandonov49/java-tools.git
