//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.12 at 11:11:03 PM EET 
//


package net.ifao.application.communication.obex.v4;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="destination" type="{}String" /&gt;
 *       &lt;attribute name="destinationCountryCode" type="{}String" /&gt;
 *       &lt;attribute name="privUntilDate" type="{}DateTime" /&gt;
 *       &lt;attribute name="privFromDate" type="{}DateTime" /&gt;
 *       &lt;attribute name="untilDate" type="{}DateTime" /&gt;
 *       &lt;attribute name="fromDate" type="{}DateTime" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ExpenseData")
public class ExpenseData {

    @XmlAttribute(name = "destination")
    protected String destination;
    @XmlAttribute(name = "destinationCountryCode")
    protected String destinationCountryCode;
    @XmlAttribute(name = "privUntilDate")
    protected String privUntilDate;
    @XmlAttribute(name = "privFromDate")
    protected String privFromDate;
    @XmlAttribute(name = "untilDate")
    protected String untilDate;
    @XmlAttribute(name = "fromDate")
    protected String fromDate;

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the destinationCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationCountryCode() {
        return destinationCountryCode;
    }

    /**
     * Sets the value of the destinationCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationCountryCode(String value) {
        this.destinationCountryCode = value;
    }

    /**
     * Gets the value of the privUntilDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivUntilDate() {
        return privUntilDate;
    }

    /**
     * Sets the value of the privUntilDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivUntilDate(String value) {
        this.privUntilDate = value;
    }

    /**
     * Gets the value of the privFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivFromDate() {
        return privFromDate;
    }

    /**
     * Sets the value of the privFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivFromDate(String value) {
        this.privFromDate = value;
    }

    /**
     * Gets the value of the untilDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUntilDate() {
        return untilDate;
    }

    /**
     * Sets the value of the untilDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUntilDate(String value) {
        this.untilDate = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromDate(String value) {
        this.fromDate = value;
    }

}
