//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.12 at 11:11:03 PM EET 
//


package net.ifao.application.communication.obex.v4;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}AirSubsegments"/&gt;
 *         &lt;element ref="{}HighestFare" minOccurs="0"/&gt;
 *         &lt;element ref="{}LowestFare" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ticketingDate" type="{}DateTime" /&gt;
 *       &lt;attribute name="ticketIssued" type="{}Tristate" /&gt;
 *       &lt;attribute name="ticketType" type="{}EnumAirTicketType" /&gt;
 *       &lt;attribute name="isOption" type="{}Boolean" /&gt;
 *       &lt;attribute name="preferred" type="{}Boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "airSubsegments",
    "highestFare",
    "lowestFare"
})
@XmlRootElement(name = "TripDetailsAir")
public class TripDetailsAir {

    @XmlElement(name = "AirSubsegments", required = true)
    protected AirSubsegments airSubsegments;
    @XmlElement(name = "HighestFare")
    protected HighestFare highestFare;
    @XmlElement(name = "LowestFare")
    protected LowestFare lowestFare;
    @XmlAttribute(name = "ticketingDate")
    protected String ticketingDate;
    @XmlAttribute(name = "ticketIssued")
    protected String ticketIssued;
    @XmlAttribute(name = "ticketType")
    protected EnumAirTicketType ticketType;
    @XmlAttribute(name = "isOption")
    protected String isOption;
    @XmlAttribute(name = "preferred")
    protected String preferred;

    /**
     * Gets the value of the airSubsegments property.
     * 
     * @return
     *     possible object is
     *     {@link AirSubsegments }
     *     
     */
    public AirSubsegments getAirSubsegments() {
        return airSubsegments;
    }

    /**
     * Sets the value of the airSubsegments property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirSubsegments }
     *     
     */
    public void setAirSubsegments(AirSubsegments value) {
        this.airSubsegments = value;
    }

    /**
     * Gets the value of the highestFare property.
     * 
     * @return
     *     possible object is
     *     {@link HighestFare }
     *     
     */
    public HighestFare getHighestFare() {
        return highestFare;
    }

    /**
     * Sets the value of the highestFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighestFare }
     *     
     */
    public void setHighestFare(HighestFare value) {
        this.highestFare = value;
    }

    /**
     * Gets the value of the lowestFare property.
     * 
     * @return
     *     possible object is
     *     {@link LowestFare }
     *     
     */
    public LowestFare getLowestFare() {
        return lowestFare;
    }

    /**
     * Sets the value of the lowestFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link LowestFare }
     *     
     */
    public void setLowestFare(LowestFare value) {
        this.lowestFare = value;
    }

    /**
     * Gets the value of the ticketingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketingDate() {
        return ticketingDate;
    }

    /**
     * Sets the value of the ticketingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketingDate(String value) {
        this.ticketingDate = value;
    }

    /**
     * Gets the value of the ticketIssued property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketIssued() {
        return ticketIssued;
    }

    /**
     * Sets the value of the ticketIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketIssued(String value) {
        this.ticketIssued = value;
    }

    /**
     * Gets the value of the ticketType property.
     * 
     * @return
     *     possible object is
     *     {@link EnumAirTicketType }
     *     
     */
    public EnumAirTicketType getTicketType() {
        return ticketType;
    }

    /**
     * Sets the value of the ticketType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumAirTicketType }
     *     
     */
    public void setTicketType(EnumAirTicketType value) {
        this.ticketType = value;
    }

    /**
     * Gets the value of the isOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsOption() {
        return isOption;
    }

    /**
     * Sets the value of the isOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsOption(String value) {
        this.isOption = value;
    }

    /**
     * Gets the value of the preferred property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferred() {
        return preferred;
    }

    /**
     * Sets the value of the preferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferred(String value) {
        this.preferred = value;
    }

}
