//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.06.18 at 01:39:50 AM EEST
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}present" minOccurs="0"/&gt;
 *         &lt;element ref="{}stereo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "present",
    "stereo"
})
@XmlRootElement(name = "audio")
public class Audio {

  protected String present;
  protected String stereo;

  /**
   * Gets the value of the present property.
   * 
   * @return possible object is {@link String }
   */
  public String getPresent() {
    return present;
  }

  /**
   * Sets the value of the present property.
   * 
   * @param value
   *          allowed object is {@link String }
   */
  public void setPresent(String value) {
    this.present = value;
  }

  /**
   * Gets the value of the stereo property.
   * 
   * @return possible object is {@link String }
   */
  public String getStereo() {
    return stereo;
  }

  /**
   * Sets the value of the stereo property.
   * 
   * @param value
   *          allowed object is {@link String }
   */
  public void setStereo(String value) {
    this.stereo = value;
  }

}
