//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.06.18 at 01:39:50 AM EEST
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attGroup ref="{}attlist.image"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "image")
public class Image {

  @XmlValue
  protected String content;
  @XmlAttribute(name = "type")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String type;
  @XmlAttribute(name = "size")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String size;
  @XmlAttribute(name = "orient")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String orient;
  @XmlAttribute(name = "system")
  @XmlSchemaType(name = "anySimpleType")
  protected String system;

  /**
   * Gets the value of the content property.
   * 
   * @return possible object is {@link String }
   */
  public String getContent() {
    return content;
  }

  /**
   * Sets the value of the content property.
   * 
   * @param value
   *          allowed object is {@link String }
   */
  public void setContent(String value) {
    this.content = value;
  }

  /**
   * Gets the value of the type property.
   * 
   * @return possible object is {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   * 
   * @param value
   *          allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the size property.
   * 
   * @return possible object is {@link String }
   */
  public String getSize() {
    return size;
  }

  /**
   * Sets the value of the size property.
   * 
   * @param value
   *          allowed object is {@link String }
   */
  public void setSize(String value) {
    this.size = value;
  }

  /**
   * Gets the value of the orient property.
   * 
   * @return possible object is {@link String }
   */
  public String getOrient() {
    return orient;
  }

  /**
   * Sets the value of the orient property.
   * 
   * @param value
   *          allowed object is {@link String }
   */
  public void setOrient(String value) {
    this.orient = value;
  }

  /**
   * Gets the value of the system property.
   * 
   * @return possible object is {@link String }
   */
  public String getSystem() {
    return system;
  }

  /**
   * Sets the value of the system property.
   * 
   * @param value
   *          allowed object is {@link String }
   */
  public void setSystem(String value) {
    this.system = value;
  }

}
