//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.06.18 at 01:39:50 AM EEST
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attGroup ref="{}attlist.length"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "length")
public class Length {

  @XmlValue
  protected String content;
  @XmlAttribute(name = "units", required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String units;

  /**
   * Gets the value of the content property.
   * 
   * @return possible object is {@link String }
   */
  public String getContent() {
    return content;
  }

  /**
   * Sets the value of the content property.
   * 
   * @param value
   *          allowed object is {@link String }
   */
  public void setContent(String value) {
    this.content = value;
  }

  /**
   * Gets the value of the units property.
   * 
   * @return possible object is {@link String }
   */
  public String getUnits() {
    return units;
  }

  /**
   * Sets the value of the units property.
   * 
   * @param value
   *          allowed object is {@link String }
   */
  public void setUnits(String value) {
    this.units = value;
  }

}
