//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.13 at 07:31:06 PM EEST 
//


package net.ifao.application.communication.aida.v4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.airplus.com/aida/virtualcreditcards}Error"/&gt;
 *         &lt;element ref="{http://www.airplus.com/aida/virtualcreditcards}Session"/&gt;
 *         &lt;element ref="{http://www.airplus.com/aida/virtualcreditcards}CPN"/&gt;
 *         &lt;element ref="{http://www.airplus.com/aida/virtualcreditcards}CardholderName"/&gt;
 *         &lt;element ref="{http://www.airplus.com/aida/virtualcreditcards}AVSData"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ReturnCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "error",
    "session",
    "cpn",
    "cardholderName",
    "avsData"
})
@XmlRootElement(name = "AidaCardCreationResponse")
public class AidaCardCreationResponse {

    @XmlElement(name = "Error", required = true)
    protected Error error;
    @XmlElement(name = "Session", required = true)
    protected Session session;
    @XmlElement(name = "CPN", required = true)
    protected CPN cpn;
    @XmlElement(name = "CardholderName", required = true)
    protected String cardholderName;
    @XmlElement(name = "AVSData", required = true)
    protected AVSData avsData;
    @XmlAttribute(name = "ReturnCode")
    protected String returnCode;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the session property.
     * 
     * @return
     *     possible object is
     *     {@link Session }
     *     
     */
    public Session getSession() {
        return session;
    }

    /**
     * Sets the value of the session property.
     * 
     * @param value
     *     allowed object is
     *     {@link Session }
     *     
     */
    public void setSession(Session value) {
        this.session = value;
    }

    /**
     * Gets the value of the cpn property.
     * 
     * @return
     *     possible object is
     *     {@link CPN }
     *     
     */
    public CPN getCPN() {
        return cpn;
    }

    /**
     * Sets the value of the cpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPN }
     *     
     */
    public void setCPN(CPN value) {
        this.cpn = value;
    }

    /**
     * Gets the value of the cardholderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderName() {
        return cardholderName;
    }

    /**
     * Sets the value of the cardholderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderName(String value) {
        this.cardholderName = value;
    }

    /**
     * Gets the value of the avsData property.
     * 
     * @return
     *     possible object is
     *     {@link AVSData }
     *     
     */
    public AVSData getAVSData() {
        return avsData;
    }

    /**
     * Sets the value of the avsData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AVSData }
     *     
     */
    public void setAVSData(AVSData value) {
        this.avsData = value;
    }

    /**
     * Gets the value of the returnCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * Sets the value of the returnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnCode(String value) {
        this.returnCode = value;
    }

    @Override
    public String toString() {
        return "AidaCardCreationResponse{" +
                "error=" + error +
                ", session=" + session +
                ", cpn=" + cpn +
                ", cardholderName='" + cardholderName + '\'' +
                ", avsData=" + avsData +
                ", returnCode='" + returnCode + '\'' +
                '}';
    }
}
