//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.13 at 07:31:06 PM EEST 
//


package net.ifao.application.communication.aida.v4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="AVV" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PAN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Expiry" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "CPN")
public class CPN {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "AVV")
    protected String avv;
    @XmlAttribute(name = "PAN")
    protected String pan;
    @XmlAttribute(name = "Expiry")
    protected String expiry;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the avv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVV() {
        return avv;
    }

    /**
     * Sets the value of the avv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVV(String value) {
        this.avv = value;
    }

    /**
     * Gets the value of the pan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAN() {
        return pan;
    }

    /**
     * Sets the value of the pan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAN(String value) {
        this.pan = value;
    }

    /**
     * Gets the value of the expiry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiry() {
        return expiry;
    }

    /**
     * Sets the value of the expiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiry(String value) {
        this.expiry = value;
    }

    @Override
    public String toString() {
        return "CPN{" +
                "value='" + value + '\'' +
                ", avv='" + avv + '\'' +
                ", pan='" + pan + '\'' +
                ", expiry='" + expiry + '\'' +
                '}';
    }
}
