//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for aliasType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="aliasType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="updatefreq" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="descr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="detail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "aliasType",
    propOrder = {"nameOrUrlOrUpdatefreq"})
public class AliasType {

  @XmlElementRefs({
    @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "url", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "updatefreq", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "address", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "descr", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "type", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "detail", type = JAXBElement.class, required = false)
  })
  protected List<JAXBElement<? extends Serializable>> nameOrUrlOrUpdatefreq;

  /**
   * Gets the value of the nameOrUrlOrUpdatefreq property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the Jakarta XML Binding
   * object. This is why there is not a <CODE>set</CODE> method for the nameOrUrlOrUpdatefreq
   * property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getNameOrUrlOrUpdatefreq().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link
   * Byte }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement
   * }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String
   * }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >}
   */
  public List<JAXBElement<? extends Serializable>> getNameOrUrlOrUpdatefreq() {
    if (nameOrUrlOrUpdatefreq == null) {
      nameOrUrlOrUpdatefreq = new ArrayList<JAXBElement<? extends Serializable>>();
    }
    return this.nameOrUrlOrUpdatefreq;
  }
}
