//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for bindviewsType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="bindviewsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="config" type="{}configType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "bindviewsType",
    propOrder = {"config"})
public class BindviewsType {

  @XmlElement(required = true)
  protected ConfigType config;

  /**
   * Gets the value of the config property.
   *
   * @return possible object is {@link ConfigType }
   */
  public ConfigType getConfig() {
    return config;
  }

  /**
   * Sets the value of the config property.
   *
   * @param value allowed object is {@link ConfigType }
   */
  public void setConfig(ConfigType value) {
    this.config = value;
  }
}
