//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for certexpireType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="certexpireType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="enable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ignore_revoked" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="expiredays" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "certexpireType",
    propOrder = {"enable", "ignoreRevoked", "expiredays"})
public class CertexpireType {

  @XmlElement(required = true)
  protected String enable;

  @XmlElement(name = "ignore_revoked", required = true)
  protected String ignoreRevoked;

  protected byte expiredays;

  /**
   * Gets the value of the enable property.
   *
   * @return possible object is {@link String }
   */
  public String getEnable() {
    return enable;
  }

  /**
   * Sets the value of the enable property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEnable(String value) {
    this.enable = value;
  }

  /**
   * Gets the value of the ignoreRevoked property.
   *
   * @return possible object is {@link String }
   */
  public String getIgnoreRevoked() {
    return ignoreRevoked;
  }

  /**
   * Sets the value of the ignoreRevoked property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIgnoreRevoked(String value) {
    this.ignoreRevoked = value;
  }

  /** Gets the value of the expiredays property. */
  public byte getExpiredays() {
    return expiredays;
  }

  /** Sets the value of the expiredays property. */
  public void setExpiredays(byte value) {
    this.expiredays = value;
  }
}
