//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for ezshaperType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ezshaperType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="step1" type="{}step1Type"/&gt;
 *         &lt;element name="step2" type="{}step2Type"/&gt;
 *         &lt;element name="step5" type="{}step5Type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ezshaperType",
    propOrder = {"step1", "step2", "step5"})
public class EzshaperType {

  @XmlElement(required = true)
  protected Step1Type step1;

  @XmlElement(required = true)
  protected Step2Type step2;

  @XmlElement(required = true)
  protected Step5Type step5;

  /**
   * Gets the value of the step1 property.
   *
   * @return possible object is {@link Step1Type }
   */
  public Step1Type getStep1() {
    return step1;
  }

  /**
   * Sets the value of the step1 property.
   *
   * @param value allowed object is {@link Step1Type }
   */
  public void setStep1(Step1Type value) {
    this.step1 = value;
  }

  /**
   * Gets the value of the step2 property.
   *
   * @return possible object is {@link Step2Type }
   */
  public Step2Type getStep2() {
    return step2;
  }

  /**
   * Sets the value of the step2 property.
   *
   * @param value allowed object is {@link Step2Type }
   */
  public void setStep2(Step2Type value) {
    this.step2 = value;
  }

  /**
   * Gets the value of the step5 property.
   *
   * @return possible object is {@link Step5Type }
   */
  public Step5Type getStep5() {
    return step5;
  }

  /**
   * Sets the value of the step5 property.
   *
   * @param value allowed object is {@link Step5Type }
   */
  public void setStep5(Step5Type value) {
    this.step5 = value;
  }
}
