//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for filterType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="filterType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rule" type="{}ruleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="separator" type="{}separatorType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "filterType",
    propOrder = {"rule", "separator"})
public class FilterType {

  protected List<RuleType> rule;

  @XmlElement(required = true)
  protected SeparatorType separator;

  /**
   * Gets the value of the rule property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the Jakarta XML Binding
   * object. This is why there is not a <CODE>set</CODE> method for the rule property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getRule().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link RuleType }
   */
  public List<RuleType> getRule() {
    if (rule == null) {
      rule = new ArrayList<RuleType>();
    }
    return this.rule;
  }

  /**
   * Gets the value of the separator property.
   *
   * @return possible object is {@link SeparatorType }
   */
  public SeparatorType getSeparator() {
    return separator;
  }

  /**
   * Sets the value of the separator property.
   *
   * @param value allowed object is {@link SeparatorType }
   */
  public void setSeparator(SeparatorType value) {
    this.separator = value;
  }
}
