//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.10.31 at 02:18:28 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}name"/&gt;
 *         &lt;element ref="{}description"/&gt;
 *         &lt;element ref="{}scope"/&gt;
 *         &lt;element ref="{}gid"/&gt;
 *         &lt;element ref="{}member" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}priv" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"name", "description", "scope", "gid", "member", "priv"})
@XmlRootElement(name = "group")
public class Group {

  @XmlElement(required = true)
  protected String name;

  @XmlElement(required = true)
  protected String description;

  @XmlElement(required = true)
  protected String scope;

  @XmlElement(required = true)
  protected String gid;

  protected List<String> member;
  protected String priv;

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the description property.
   *
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the scope property.
   *
   * @return possible object is {@link String }
   */
  public String getScope() {
    return scope;
  }

  /**
   * Sets the value of the scope property.
   *
   * @param value allowed object is {@link String }
   */
  public void setScope(String value) {
    this.scope = value;
  }

  /**
   * Gets the value of the gid property.
   *
   * @return possible object is {@link String }
   */
  public String getGid() {
    return gid;
  }

  /**
   * Sets the value of the gid property.
   *
   * @param value allowed object is {@link String }
   */
  public void setGid(String value) {
    this.gid = value;
  }

  /**
   * Gets the value of the member property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the Jakarta XML Binding
   * object. This is why there is not a <CODE>set</CODE> method for the member property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getMember().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link String }
   */
  public List<String> getMember() {
    if (member == null) {
      member = new ArrayList<String>();
    }
    return this.member;
  }

  /**
   * Gets the value of the priv property.
   *
   * @return possible object is {@link String }
   */
  public String getPriv() {
    return priv;
  }

  /**
   * Sets the value of the priv property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPriv(String value) {
    this.priv = value;
  }
}
