//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import eu.ad4ubg.adapters.CDATAAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for groupType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="groupType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="scope" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gid" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="member" type="{http://www.w3.org/2001/XMLSchema}short" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="priv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "groupType",
    propOrder = {"name", "description", "scope", "gid", "member", "priv"})
public class GroupType {

  @XmlElement(required = true)
  protected String name;

  @XmlElement(required = true)
  @XmlJavaTypeAdapter(CDATAAdapter.class)
  protected String description;

  @XmlElement(required = true)
  protected String scope;

  protected short gid;

  @XmlElement(type = Short.class)
  protected List<Short> member;

  protected String priv;

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the description property.
   *
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the scope property.
   *
   * @return possible object is {@link String }
   */
  public String getScope() {
    return scope;
  }

  /**
   * Sets the value of the scope property.
   *
   * @param value allowed object is {@link String }
   */
  public void setScope(String value) {
    this.scope = value;
  }

  /** Gets the value of the gid property. */
  public short getGid() {
    return gid;
  }

  /** Sets the value of the gid property. */
  public void setGid(short value) {
    this.gid = value;
  }

  /**
   * Gets the value of the member property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the Jakarta XML Binding
   * object. This is why there is not a <CODE>set</CODE> method for the member property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getMember().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Short }
   */
  public List<Short> getMember() {
    if (member == null) {
      member = new ArrayList<Short>();
    }
    return this.member;
  }

  /**
   * Gets the value of the priv property.
   *
   * @return possible object is {@link String }
   */
  public String getPriv() {
    return priv;
  }

  /**
   * Sets the value of the priv property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPriv(String value) {
    this.priv = value;
  }
}
