//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import eu.ad4ubg.adapters.CDATAAdapter;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlMixed;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for itemType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="itemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mday" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="wday" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="who" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="command" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="addresses" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="row" type="{}rowType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="allowedips" type="{}allowedipsType" minOccurs="0"/&gt;
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tun" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="descr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="listenport" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="privatekey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="endpoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="persistentkeepalive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="publickey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mtu" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="presharedkey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "itemType",
    propOrder = {
      "minute",
      "hour",
      "mday",
      "month",
      "wday",
      "who",
      "command",
      "type",
      "addresses",
      "name",
      "allowedips",
      "enabled",
      "tun",
      "descr",
      "listenport",
      "privatekey",
      "endpoint",
      "port",
      "persistentkeepalive",
      "publickey",
      "mtu",
      "presharedkey"
    })
public class ItemType {

  protected String minute;
  protected String hour;
  protected String mday;
  protected String month;
  protected String wday;
  protected String who;
  protected String command;
  protected String type;
  protected ItemType.Addresses addresses;
  protected String name;
  protected AllowedipsType allowedips;
  protected String enabled;
  protected String tun;

  @XmlJavaTypeAdapter(CDATAAdapter.class)
  protected String descr;

  protected Integer listenport;
  protected String privatekey;
  protected String endpoint;
  protected Integer port;
  protected String persistentkeepalive;
  protected String publickey;
  protected Short mtu;
  protected String presharedkey;

  /**
   * Gets the value of the minute property.
   *
   * @return possible object is {@link String }
   */
  public String getMinute() {
    return minute;
  }

  /**
   * Sets the value of the minute property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMinute(String value) {
    this.minute = value;
  }

  /**
   * Gets the value of the hour property.
   *
   * @return possible object is {@link String }
   */
  public String getHour() {
    return hour;
  }

  /**
   * Sets the value of the hour property.
   *
   * @param value allowed object is {@link String }
   */
  public void setHour(String value) {
    this.hour = value;
  }

  /**
   * Gets the value of the mday property.
   *
   * @return possible object is {@link String }
   */
  public String getMday() {
    return mday;
  }

  /**
   * Sets the value of the mday property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMday(String value) {
    this.mday = value;
  }

  /**
   * Gets the value of the month property.
   *
   * @return possible object is {@link String }
   */
  public String getMonth() {
    return month;
  }

  /**
   * Sets the value of the month property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMonth(String value) {
    this.month = value;
  }

  /**
   * Gets the value of the wday property.
   *
   * @return possible object is {@link String }
   */
  public String getWday() {
    return wday;
  }

  /**
   * Sets the value of the wday property.
   *
   * @param value allowed object is {@link String }
   */
  public void setWday(String value) {
    this.wday = value;
  }

  /**
   * Gets the value of the who property.
   *
   * @return possible object is {@link String }
   */
  public String getWho() {
    return who;
  }

  /**
   * Sets the value of the who property.
   *
   * @param value allowed object is {@link String }
   */
  public void setWho(String value) {
    this.who = value;
  }

  /**
   * Gets the value of the command property.
   *
   * @return possible object is {@link String }
   */
  public String getCommand() {
    return command;
  }

  /**
   * Sets the value of the command property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCommand(String value) {
    this.command = value;
  }

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the addresses property.
   *
   * @return possible object is {@link ItemType.Addresses }
   */
  public ItemType.Addresses getAddresses() {
    return addresses;
  }

  /**
   * Sets the value of the addresses property.
   *
   * @param value allowed object is {@link ItemType.Addresses }
   */
  public void setAddresses(ItemType.Addresses value) {
    this.addresses = value;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the allowedips property.
   *
   * @return possible object is {@link AllowedipsType }
   */
  public AllowedipsType getAllowedips() {
    return allowedips;
  }

  /**
   * Sets the value of the allowedips property.
   *
   * @param value allowed object is {@link AllowedipsType }
   */
  public void setAllowedips(AllowedipsType value) {
    this.allowedips = value;
  }

  /**
   * Gets the value of the enabled property.
   *
   * @return possible object is {@link String }
   */
  public String getEnabled() {
    return enabled;
  }

  /**
   * Sets the value of the enabled property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEnabled(String value) {
    this.enabled = value;
  }

  /**
   * Gets the value of the tun property.
   *
   * @return possible object is {@link String }
   */
  public String getTun() {
    return tun;
  }

  /**
   * Sets the value of the tun property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTun(String value) {
    this.tun = value;
  }

  /**
   * Gets the value of the descr property.
   *
   * @return possible object is {@link String }
   */
  public String getDescr() {
    return descr;
  }

  /**
   * Sets the value of the descr property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescr(String value) {
    this.descr = value;
  }

  /**
   * Gets the value of the listenport property.
   *
   * @return possible object is {@link Integer }
   */
  public Integer getListenport() {
    return listenport;
  }

  /**
   * Sets the value of the listenport property.
   *
   * @param value allowed object is {@link Integer }
   */
  public void setListenport(Integer value) {
    this.listenport = value;
  }

  /**
   * Gets the value of the privatekey property.
   *
   * @return possible object is {@link String }
   */
  public String getPrivatekey() {
    return privatekey;
  }

  /**
   * Sets the value of the privatekey property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPrivatekey(String value) {
    this.privatekey = value;
  }

  /**
   * Gets the value of the endpoint property.
   *
   * @return possible object is {@link String }
   */
  public String getEndpoint() {
    return endpoint;
  }

  /**
   * Sets the value of the endpoint property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEndpoint(String value) {
    this.endpoint = value;
  }

  /**
   * Gets the value of the port property.
   *
   * @return possible object is {@link Integer }
   */
  public Integer getPort() {
    return port;
  }

  /**
   * Sets the value of the port property.
   *
   * @param value allowed object is {@link Integer }
   */
  public void setPort(Integer value) {
    this.port = value;
  }

  /**
   * Gets the value of the persistentkeepalive property.
   *
   * @return possible object is {@link String }
   */
  public String getPersistentkeepalive() {
    return persistentkeepalive;
  }

  /**
   * Sets the value of the persistentkeepalive property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPersistentkeepalive(String value) {
    this.persistentkeepalive = value;
  }

  /**
   * Gets the value of the publickey property.
   *
   * @return possible object is {@link String }
   */
  public String getPublickey() {
    return publickey;
  }

  /**
   * Sets the value of the publickey property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPublickey(String value) {
    this.publickey = value;
  }

  /**
   * Gets the value of the mtu property.
   *
   * @return possible object is {@link Short }
   */
  public Short getMtu() {
    return mtu;
  }

  /**
   * Sets the value of the mtu property.
   *
   * @param value allowed object is {@link Short }
   */
  public void setMtu(Short value) {
    this.mtu = value;
  }

  /**
   * Gets the value of the presharedkey property.
   *
   * @return possible object is {@link String }
   */
  public String getPresharedkey() {
    return presharedkey;
  }

  /**
   * Sets the value of the presharedkey property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPresharedkey(String value) {
    this.presharedkey = value;
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="row" type="{}rowType" minOccurs="0"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"content"})
  public static class Addresses {

    @XmlElementRef(name = "row", type = JAXBElement.class, required = false)
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the Jakarta XML Binding
     * object. This is why there is not a <CODE>set</CODE> method for the content property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code
     * <}{@link RowType }{@code >} {@link String }
     */
    public List<Serializable> getContent() {
      if (content == null) {
        content = new ArrayList<Serializable>();
      }
      return this.content;
    }
  }
}
