//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.10.31 at 02:18:28 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlMixed;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}minute" minOccurs="0"/&gt;
 *         &lt;element ref="{}hour" minOccurs="0"/&gt;
 *         &lt;element ref="{}mday" minOccurs="0"/&gt;
 *         &lt;element ref="{}month" minOccurs="0"/&gt;
 *         &lt;element ref="{}wday" minOccurs="0"/&gt;
 *         &lt;element ref="{}who" minOccurs="0"/&gt;
 *         &lt;element ref="{}command" minOccurs="0"/&gt;
 *         &lt;element ref="{}type" minOccurs="0"/&gt;
 *         &lt;element ref="{}addresses" minOccurs="0"/&gt;
 *         &lt;element ref="{}name" minOccurs="0"/&gt;
 *         &lt;element ref="{}allowedips" minOccurs="0"/&gt;
 *         &lt;element ref="{}enabled" minOccurs="0"/&gt;
 *         &lt;element ref="{}tun" minOccurs="0"/&gt;
 *         &lt;element ref="{}descr" minOccurs="0"/&gt;
 *         &lt;element ref="{}listenport" minOccurs="0"/&gt;
 *         &lt;element ref="{}privatekey" minOccurs="0"/&gt;
 *         &lt;element ref="{}endpoint" minOccurs="0"/&gt;
 *         &lt;element ref="{}port" minOccurs="0"/&gt;
 *         &lt;element ref="{}persistentkeepalive" minOccurs="0"/&gt;
 *         &lt;element ref="{}publickey" minOccurs="0"/&gt;
 *         &lt;element ref="{}mtu" minOccurs="0"/&gt;
 *         &lt;element ref="{}presharedkey" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"content"})
@XmlRootElement(name = "item")
public class Item {

  @XmlElementRefs({
    @XmlElementRef(name = "minute", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "hour", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "mday", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "month", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "wday", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "who", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "command", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "type", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "addresses", type = Addresses.class, required = false),
    @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "allowedips", type = Allowedips.class, required = false),
    @XmlElementRef(name = "enabled", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "tun", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "descr", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "listenport", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "privatekey", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "endpoint", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "port", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "persistentkeepalive", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "publickey", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "mtu", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "presharedkey", type = JAXBElement.class, required = false)
  })
  @XmlMixed
  protected List<Object> content;

  /**
   * Gets the value of the content property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the Jakarta XML Binding
   * object. This is why there is not a <CODE>set</CODE> method for the content property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getContent().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Addresses } {@link
   * Allowedips } {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code
   * <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String
   * }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code
   * <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String
   * }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code
   * <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String
   * }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code
   * <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String
   * }{@code >} {@link String }
   */
  public List<Object> getContent() {
    if (content == null) {
      content = new ArrayList<Object>();
    }
    return this.content;
  }
}
