//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.10.31 at 02:18:28 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{}name"/&gt;
 *         &lt;element ref="{}tooltiptext"/&gt;
 *         &lt;element ref="{}section"/&gt;
 *         &lt;element ref="{}url"/&gt;
 *         &lt;element ref="{}configfile"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"nameOrTooltiptextOrSection"})
@XmlRootElement(name = "menu")
public class Menu {

  @XmlElementRefs({
    @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "tooltiptext", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "section", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "url", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "configfile", type = JAXBElement.class, required = false)
  })
  protected List<JAXBElement<String>> nameOrTooltiptextOrSection;

  /**
   * Gets the value of the nameOrTooltiptextOrSection property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the Jakarta XML Binding
   * object. This is why there is not a <CODE>set</CODE> method for the nameOrTooltiptextOrSection
   * property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getNameOrTooltiptextOrSection().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link
   * String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement
   * }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >}
   */
  public List<JAXBElement<String>> getNameOrTooltiptextOrSection() {
    if (nameOrTooltiptextOrSection == null) {
      nameOrTooltiptextOrSection = new ArrayList<JAXBElement<String>>();
    }
    return this.nameOrTooltiptextOrSection;
  }
}
