//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.10.31 at 02:18:28 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}descr"/&gt;
 *         &lt;element ref="{}if"/&gt;
 *         &lt;element ref="{}spoofmac"/&gt;
 *         &lt;element ref="{}enable"/&gt;
 *         &lt;element ref="{}ipaddr"/&gt;
 *         &lt;element ref="{}subnet"/&gt;
 *         &lt;element ref="{}gateway"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"descr", "_if", "spoofmac", "enable", "ipaddr", "subnet", "gateway"})
@XmlRootElement(name = "opt7")
public class Opt7 {

  @XmlElement(required = true)
  protected String descr;

  @XmlElement(name = "if", required = true)
  protected String _if;

  @XmlElement(required = true)
  protected String spoofmac;

  @XmlElement(required = true)
  protected String enable;

  @XmlElement(required = true)
  protected String ipaddr;

  @XmlElement(required = true)
  protected String subnet;

  @XmlElement(required = true)
  protected String gateway;

  /**
   * Gets the value of the descr property.
   *
   * @return possible object is {@link String }
   */
  public String getDescr() {
    return descr;
  }

  /**
   * Sets the value of the descr property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescr(String value) {
    this.descr = value;
  }

  /**
   * Gets the value of the if property.
   *
   * @return possible object is {@link String }
   */
  public String getIf() {
    return _if;
  }

  /**
   * Sets the value of the if property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIf(String value) {
    this._if = value;
  }

  /**
   * Gets the value of the spoofmac property.
   *
   * @return possible object is {@link String }
   */
  public String getSpoofmac() {
    return spoofmac;
  }

  /**
   * Sets the value of the spoofmac property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSpoofmac(String value) {
    this.spoofmac = value;
  }

  /**
   * Gets the value of the enable property.
   *
   * @return possible object is {@link String }
   */
  public String getEnable() {
    return enable;
  }

  /**
   * Sets the value of the enable property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEnable(String value) {
    this.enable = value;
  }

  /**
   * Gets the value of the ipaddr property.
   *
   * @return possible object is {@link String }
   */
  public String getIpaddr() {
    return ipaddr;
  }

  /**
   * Sets the value of the ipaddr property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIpaddr(String value) {
    this.ipaddr = value;
  }

  /**
   * Gets the value of the subnet property.
   *
   * @return possible object is {@link String }
   */
  public String getSubnet() {
    return subnet;
  }

  /**
   * Sets the value of the subnet property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSubnet(String value) {
    this.subnet = value;
  }

  /**
   * Gets the value of the gateway property.
   *
   * @return possible object is {@link String }
   */
  public String getGateway() {
    return gateway;
  }

  /**
   * Sets the value of the gateway property.
   *
   * @param value allowed object is {@link String }
   */
  public void setGateway(String value) {
    this.gateway = value;
  }
}
