//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.10.31 at 02:18:28 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}range"/&gt;
 *         &lt;element ref="{}descr"/&gt;
 *         &lt;element ref="{}defaultleasetime"/&gt;
 *         &lt;element ref="{}maxleasetime"/&gt;
 *         &lt;element ref="{}netmask"/&gt;
 *         &lt;element ref="{}gateway"/&gt;
 *         &lt;element ref="{}domain"/&gt;
 *         &lt;element ref="{}domainsearchlist"/&gt;
 *         &lt;element ref="{}ddnsdomain"/&gt;
 *         &lt;element ref="{}ddnsdomainprimary"/&gt;
 *         &lt;element ref="{}ddnsdomainprimaryport"/&gt;
 *         &lt;element ref="{}ddnsdomainsecondary"/&gt;
 *         &lt;element ref="{}ddnsdomainsecondaryport"/&gt;
 *         &lt;element ref="{}ddnsdomainkeyname"/&gt;
 *         &lt;element ref="{}ddnsdomainkeyalgorithm"/&gt;
 *         &lt;element ref="{}ddnsdomainkey"/&gt;
 *         &lt;element ref="{}mac_allow"/&gt;
 *         &lt;element ref="{}mac_deny"/&gt;
 *         &lt;element ref="{}ddnsclientupdates"/&gt;
 *         &lt;element ref="{}tftp"/&gt;
 *         &lt;element ref="{}ldap"/&gt;
 *         &lt;element ref="{}nextserver"/&gt;
 *         &lt;element ref="{}filename"/&gt;
 *         &lt;element ref="{}filename32"/&gt;
 *         &lt;element ref="{}filename64"/&gt;
 *         &lt;element ref="{}filename32arm"/&gt;
 *         &lt;element ref="{}filename64arm"/&gt;
 *         &lt;element ref="{}uefihttpboot"/&gt;
 *         &lt;element ref="{}rootpath"/&gt;
 *         &lt;element ref="{}numberoptions"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {
      "range",
      "descr",
      "defaultleasetime",
      "maxleasetime",
      "netmask",
      "gateway",
      "domain",
      "domainsearchlist",
      "ddnsdomain",
      "ddnsdomainprimary",
      "ddnsdomainprimaryport",
      "ddnsdomainsecondary",
      "ddnsdomainsecondaryport",
      "ddnsdomainkeyname",
      "ddnsdomainkeyalgorithm",
      "ddnsdomainkey",
      "macAllow",
      "macDeny",
      "ddnsclientupdates",
      "tftp",
      "ldap",
      "nextserver",
      "filename",
      "filename32",
      "filename64",
      "filename32Arm",
      "filename64Arm",
      "uefihttpboot",
      "rootpath",
      "numberoptions"
    })
@XmlRootElement(name = "pool")
public class Pool {

  @XmlElement(required = true)
  protected Range range;

  @XmlElement(required = true)
  protected String descr;

  @XmlElement(required = true)
  protected String defaultleasetime;

  @XmlElement(required = true)
  protected String maxleasetime;

  @XmlElement(required = true)
  protected String netmask;

  @XmlElement(required = true)
  protected String gateway;

  @XmlElement(required = true)
  protected String domain;

  @XmlElement(required = true)
  protected String domainsearchlist;

  @XmlElement(required = true)
  protected String ddnsdomain;

  @XmlElement(required = true)
  protected String ddnsdomainprimary;

  @XmlElement(required = true)
  protected String ddnsdomainprimaryport;

  @XmlElement(required = true)
  protected String ddnsdomainsecondary;

  @XmlElement(required = true)
  protected String ddnsdomainsecondaryport;

  @XmlElement(required = true)
  protected String ddnsdomainkeyname;

  @XmlElement(required = true)
  protected String ddnsdomainkeyalgorithm;

  @XmlElement(required = true)
  protected String ddnsdomainkey;

  @XmlElement(name = "mac_allow", required = true)
  protected String macAllow;

  @XmlElement(name = "mac_deny", required = true)
  protected String macDeny;

  @XmlElement(required = true)
  protected String ddnsclientupdates;

  @XmlElement(required = true)
  protected String tftp;

  @XmlElement(required = true)
  protected String ldap;

  @XmlElement(required = true)
  protected String nextserver;

  @XmlElement(required = true)
  protected String filename;

  @XmlElement(required = true)
  protected String filename32;

  @XmlElement(required = true)
  protected String filename64;

  @XmlElement(name = "filename32arm", required = true)
  protected String filename32Arm;

  @XmlElement(name = "filename64arm", required = true)
  protected String filename64Arm;

  @XmlElement(required = true)
  protected String uefihttpboot;

  @XmlElement(required = true)
  protected String rootpath;

  @XmlElement(required = true)
  protected String numberoptions;

  /**
   * Gets the value of the range property.
   *
   * @return possible object is {@link Range }
   */
  public Range getRange() {
    return range;
  }

  /**
   * Sets the value of the range property.
   *
   * @param value allowed object is {@link Range }
   */
  public void setRange(Range value) {
    this.range = value;
  }

  /**
   * Gets the value of the descr property.
   *
   * @return possible object is {@link String }
   */
  public String getDescr() {
    return descr;
  }

  /**
   * Sets the value of the descr property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescr(String value) {
    this.descr = value;
  }

  /**
   * Gets the value of the defaultleasetime property.
   *
   * @return possible object is {@link String }
   */
  public String getDefaultleasetime() {
    return defaultleasetime;
  }

  /**
   * Sets the value of the defaultleasetime property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDefaultleasetime(String value) {
    this.defaultleasetime = value;
  }

  /**
   * Gets the value of the maxleasetime property.
   *
   * @return possible object is {@link String }
   */
  public String getMaxleasetime() {
    return maxleasetime;
  }

  /**
   * Sets the value of the maxleasetime property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMaxleasetime(String value) {
    this.maxleasetime = value;
  }

  /**
   * Gets the value of the netmask property.
   *
   * @return possible object is {@link String }
   */
  public String getNetmask() {
    return netmask;
  }

  /**
   * Sets the value of the netmask property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNetmask(String value) {
    this.netmask = value;
  }

  /**
   * Gets the value of the gateway property.
   *
   * @return possible object is {@link String }
   */
  public String getGateway() {
    return gateway;
  }

  /**
   * Sets the value of the gateway property.
   *
   * @param value allowed object is {@link String }
   */
  public void setGateway(String value) {
    this.gateway = value;
  }

  /**
   * Gets the value of the domain property.
   *
   * @return possible object is {@link String }
   */
  public String getDomain() {
    return domain;
  }

  /**
   * Sets the value of the domain property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDomain(String value) {
    this.domain = value;
  }

  /**
   * Gets the value of the domainsearchlist property.
   *
   * @return possible object is {@link String }
   */
  public String getDomainsearchlist() {
    return domainsearchlist;
  }

  /**
   * Sets the value of the domainsearchlist property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDomainsearchlist(String value) {
    this.domainsearchlist = value;
  }

  /**
   * Gets the value of the ddnsdomain property.
   *
   * @return possible object is {@link String }
   */
  public String getDdnsdomain() {
    return ddnsdomain;
  }

  /**
   * Sets the value of the ddnsdomain property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDdnsdomain(String value) {
    this.ddnsdomain = value;
  }

  /**
   * Gets the value of the ddnsdomainprimary property.
   *
   * @return possible object is {@link String }
   */
  public String getDdnsdomainprimary() {
    return ddnsdomainprimary;
  }

  /**
   * Sets the value of the ddnsdomainprimary property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDdnsdomainprimary(String value) {
    this.ddnsdomainprimary = value;
  }

  /**
   * Gets the value of the ddnsdomainprimaryport property.
   *
   * @return possible object is {@link String }
   */
  public String getDdnsdomainprimaryport() {
    return ddnsdomainprimaryport;
  }

  /**
   * Sets the value of the ddnsdomainprimaryport property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDdnsdomainprimaryport(String value) {
    this.ddnsdomainprimaryport = value;
  }

  /**
   * Gets the value of the ddnsdomainsecondary property.
   *
   * @return possible object is {@link String }
   */
  public String getDdnsdomainsecondary() {
    return ddnsdomainsecondary;
  }

  /**
   * Sets the value of the ddnsdomainsecondary property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDdnsdomainsecondary(String value) {
    this.ddnsdomainsecondary = value;
  }

  /**
   * Gets the value of the ddnsdomainsecondaryport property.
   *
   * @return possible object is {@link String }
   */
  public String getDdnsdomainsecondaryport() {
    return ddnsdomainsecondaryport;
  }

  /**
   * Sets the value of the ddnsdomainsecondaryport property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDdnsdomainsecondaryport(String value) {
    this.ddnsdomainsecondaryport = value;
  }

  /**
   * Gets the value of the ddnsdomainkeyname property.
   *
   * @return possible object is {@link String }
   */
  public String getDdnsdomainkeyname() {
    return ddnsdomainkeyname;
  }

  /**
   * Sets the value of the ddnsdomainkeyname property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDdnsdomainkeyname(String value) {
    this.ddnsdomainkeyname = value;
  }

  /**
   * Gets the value of the ddnsdomainkeyalgorithm property.
   *
   * @return possible object is {@link String }
   */
  public String getDdnsdomainkeyalgorithm() {
    return ddnsdomainkeyalgorithm;
  }

  /**
   * Sets the value of the ddnsdomainkeyalgorithm property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDdnsdomainkeyalgorithm(String value) {
    this.ddnsdomainkeyalgorithm = value;
  }

  /**
   * Gets the value of the ddnsdomainkey property.
   *
   * @return possible object is {@link String }
   */
  public String getDdnsdomainkey() {
    return ddnsdomainkey;
  }

  /**
   * Sets the value of the ddnsdomainkey property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDdnsdomainkey(String value) {
    this.ddnsdomainkey = value;
  }

  /**
   * Gets the value of the macAllow property.
   *
   * @return possible object is {@link String }
   */
  public String getMacAllow() {
    return macAllow;
  }

  /**
   * Sets the value of the macAllow property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMacAllow(String value) {
    this.macAllow = value;
  }

  /**
   * Gets the value of the macDeny property.
   *
   * @return possible object is {@link String }
   */
  public String getMacDeny() {
    return macDeny;
  }

  /**
   * Sets the value of the macDeny property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMacDeny(String value) {
    this.macDeny = value;
  }

  /**
   * Gets the value of the ddnsclientupdates property.
   *
   * @return possible object is {@link String }
   */
  public String getDdnsclientupdates() {
    return ddnsclientupdates;
  }

  /**
   * Sets the value of the ddnsclientupdates property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDdnsclientupdates(String value) {
    this.ddnsclientupdates = value;
  }

  /**
   * Gets the value of the tftp property.
   *
   * @return possible object is {@link String }
   */
  public String getTftp() {
    return tftp;
  }

  /**
   * Sets the value of the tftp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTftp(String value) {
    this.tftp = value;
  }

  /**
   * Gets the value of the ldap property.
   *
   * @return possible object is {@link String }
   */
  public String getLdap() {
    return ldap;
  }

  /**
   * Sets the value of the ldap property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLdap(String value) {
    this.ldap = value;
  }

  /**
   * Gets the value of the nextserver property.
   *
   * @return possible object is {@link String }
   */
  public String getNextserver() {
    return nextserver;
  }

  /**
   * Sets the value of the nextserver property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNextserver(String value) {
    this.nextserver = value;
  }

  /**
   * Gets the value of the filename property.
   *
   * @return possible object is {@link String }
   */
  public String getFilename() {
    return filename;
  }

  /**
   * Sets the value of the filename property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFilename(String value) {
    this.filename = value;
  }

  /**
   * Gets the value of the filename32 property.
   *
   * @return possible object is {@link String }
   */
  public String getFilename32() {
    return filename32;
  }

  /**
   * Sets the value of the filename32 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFilename32(String value) {
    this.filename32 = value;
  }

  /**
   * Gets the value of the filename64 property.
   *
   * @return possible object is {@link String }
   */
  public String getFilename64() {
    return filename64;
  }

  /**
   * Sets the value of the filename64 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFilename64(String value) {
    this.filename64 = value;
  }

  /**
   * Gets the value of the filename32Arm property.
   *
   * @return possible object is {@link String }
   */
  public String getFilename32Arm() {
    return filename32Arm;
  }

  /**
   * Sets the value of the filename32Arm property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFilename32Arm(String value) {
    this.filename32Arm = value;
  }

  /**
   * Gets the value of the filename64Arm property.
   *
   * @return possible object is {@link String }
   */
  public String getFilename64Arm() {
    return filename64Arm;
  }

  /**
   * Sets the value of the filename64Arm property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFilename64Arm(String value) {
    this.filename64Arm = value;
  }

  /**
   * Gets the value of the uefihttpboot property.
   *
   * @return possible object is {@link String }
   */
  public String getUefihttpboot() {
    return uefihttpboot;
  }

  /**
   * Sets the value of the uefihttpboot property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUefihttpboot(String value) {
    this.uefihttpboot = value;
  }

  /**
   * Gets the value of the rootpath property.
   *
   * @return possible object is {@link String }
   */
  public String getRootpath() {
    return rootpath;
  }

  /**
   * Sets the value of the rootpath property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRootpath(String value) {
    this.rootpath = value;
  }

  /**
   * Gets the value of the numberoptions property.
   *
   * @return possible object is {@link String }
   */
  public String getNumberoptions() {
    return numberoptions;
  }

  /**
   * Sets the value of the numberoptions property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNumberoptions(String value) {
    this.numberoptions = value;
  }
}
