//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for pushoverType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="pushoverType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="apikey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="userkey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sound" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="retry" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="expire" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "pushoverType",
    propOrder = {"apikey", "userkey", "sound", "priority", "retry", "expire"})
public class PushoverType {

  @XmlElement(required = true)
  protected String apikey;

  @XmlElement(required = true)
  protected String userkey;

  @XmlElement(required = true)
  protected String sound;

  protected byte priority;
  protected byte retry;
  protected short expire;

  /**
   * Gets the value of the apikey property.
   *
   * @return possible object is {@link String }
   */
  public String getApikey() {
    return apikey;
  }

  /**
   * Sets the value of the apikey property.
   *
   * @param value allowed object is {@link String }
   */
  public void setApikey(String value) {
    this.apikey = value;
  }

  /**
   * Gets the value of the userkey property.
   *
   * @return possible object is {@link String }
   */
  public String getUserkey() {
    return userkey;
  }

  /**
   * Sets the value of the userkey property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUserkey(String value) {
    this.userkey = value;
  }

  /**
   * Gets the value of the sound property.
   *
   * @return possible object is {@link String }
   */
  public String getSound() {
    return sound;
  }

  /**
   * Sets the value of the sound property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSound(String value) {
    this.sound = value;
  }

  /** Gets the value of the priority property. */
  public byte getPriority() {
    return priority;
  }

  /** Sets the value of the priority property. */
  public void setPriority(byte value) {
    this.priority = value;
  }

  /** Gets the value of the retry property. */
  public byte getRetry() {
    return retry;
  }

  /** Sets the value of the retry property. */
  public void setRetry(byte value) {
    this.retry = value;
  }

  /** Gets the value of the expire property. */
  public short getExpire() {
    return expire;
  }

  /** Sets the value of the expire property. */
  public void setExpire(short value) {
    this.expire = value;
  }
}
