//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import eu.ad4ubg.adapters.CDATAAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Java class for serviceType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="serviceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rcfile" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="executable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="starts_on_sync" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "serviceType",
    propOrder = {"name", "rcfile", "executable", "description", "startsOnSync"})
public class ServiceType {

  @XmlElement(required = true)
  protected String name;

  @XmlElement(required = true)
  protected String rcfile;

  @XmlElement(required = true)
  protected String executable;

  @XmlElement(required = true)
  @XmlJavaTypeAdapter(CDATAAdapter.class)
  protected String description;

  @XmlElement(name = "starts_on_sync")
  protected String startsOnSync;

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the rcfile property.
   *
   * @return possible object is {@link String }
   */
  public String getRcfile() {
    return rcfile;
  }

  /**
   * Sets the value of the rcfile property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRcfile(String value) {
    this.rcfile = value;
  }

  /**
   * Gets the value of the executable property.
   *
   * @return possible object is {@link String }
   */
  public String getExecutable() {
    return executable;
  }

  /**
   * Sets the value of the executable property.
   *
   * @param value allowed object is {@link String }
   */
  public void setExecutable(String value) {
    this.executable = value;
  }

  /**
   * Gets the value of the description property.
   *
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the startsOnSync property.
   *
   * @return possible object is {@link String }
   */
  public String getStartsOnSync() {
    return startsOnSync;
  }

  /**
   * Sets the value of the startsOnSync property.
   *
   * @param value allowed object is {@link String }
   */
  public void setStartsOnSync(String value) {
    this.startsOnSync = value;
  }
}
