//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.10.31 at 02:18:28 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}api"/&gt;
 *         &lt;element ref="{}channel"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"api", "channel"})
@XmlRootElement(name = "slack")
public class Slack {

  @XmlElement(required = true)
  protected String api;

  @XmlElement(required = true)
  protected String channel;

  /**
   * Gets the value of the api property.
   *
   * @return possible object is {@link String }
   */
  public String getApi() {
    return api;
  }

  /**
   * Sets the value of the api property.
   *
   * @param value allowed object is {@link String }
   */
  public void setApi(String value) {
    this.api = value;
  }

  /**
   * Gets the value of the channel property.
   *
   * @return possible object is {@link String }
   */
  public String getChannel() {
    return channel;
  }

  /**
   * Sets the value of the channel property.
   *
   * @param value allowed object is {@link String }
   */
  public void setChannel(String value) {
    this.channel = value;
  }
}
