//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for step1Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="step1Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numberofconnections" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="numberoflocalinterfaces" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "step1Type",
    propOrder = {"numberofconnections", "numberoflocalinterfaces"})
public class Step1Type {

  protected byte numberofconnections;
  protected byte numberoflocalinterfaces;

  /** Gets the value of the numberofconnections property. */
  public byte getNumberofconnections() {
    return numberofconnections;
  }

  /** Sets the value of the numberofconnections property. */
  public void setNumberofconnections(byte value) {
    this.numberofconnections = value;
  }

  /** Gets the value of the numberoflocalinterfaces property. */
  public byte getNumberoflocalinterfaces() {
    return numberoflocalinterfaces;
  }

  /** Sets the value of the numberoflocalinterfaces property. */
  public void setNumberoflocalinterfaces(byte value) {
    this.numberoflocalinterfaces = value;
  }
}
