//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for step2Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="step2Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="local0downloadscheduler" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="local0interface" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="conn0uploadscheduler" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="conn0upload" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="conn0uploadspeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="conn0download" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="conn0downloadspeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="conn0interface" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "step2Type",
    propOrder = {
      "local0Downloadscheduler",
      "local0Interface",
      "conn0Uploadscheduler",
      "conn0Upload",
      "conn0Uploadspeed",
      "conn0Download",
      "conn0Downloadspeed",
      "conn0Interface"
    })
public class Step2Type {

  @XmlElement(name = "local0downloadscheduler", required = true)
  protected String local0Downloadscheduler;

  @XmlElement(name = "local0interface", required = true)
  protected String local0Interface;

  @XmlElement(name = "conn0uploadscheduler", required = true)
  protected String conn0Uploadscheduler;

  @XmlElement(name = "conn0upload")
  protected short conn0Upload;

  @XmlElement(name = "conn0uploadspeed", required = true)
  protected String conn0Uploadspeed;

  @XmlElement(name = "conn0download")
  protected short conn0Download;

  @XmlElement(name = "conn0downloadspeed", required = true)
  protected String conn0Downloadspeed;

  @XmlElement(name = "conn0interface", required = true)
  protected String conn0Interface;

  /**
   * Gets the value of the local0Downloadscheduler property.
   *
   * @return possible object is {@link String }
   */
  public String getLocal0Downloadscheduler() {
    return local0Downloadscheduler;
  }

  /**
   * Sets the value of the local0Downloadscheduler property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLocal0Downloadscheduler(String value) {
    this.local0Downloadscheduler = value;
  }

  /**
   * Gets the value of the local0Interface property.
   *
   * @return possible object is {@link String }
   */
  public String getLocal0Interface() {
    return local0Interface;
  }

  /**
   * Sets the value of the local0Interface property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLocal0Interface(String value) {
    this.local0Interface = value;
  }

  /**
   * Gets the value of the conn0Uploadscheduler property.
   *
   * @return possible object is {@link String }
   */
  public String getConn0Uploadscheduler() {
    return conn0Uploadscheduler;
  }

  /**
   * Sets the value of the conn0Uploadscheduler property.
   *
   * @param value allowed object is {@link String }
   */
  public void setConn0Uploadscheduler(String value) {
    this.conn0Uploadscheduler = value;
  }

  /** Gets the value of the conn0Upload property. */
  public short getConn0Upload() {
    return conn0Upload;
  }

  /** Sets the value of the conn0Upload property. */
  public void setConn0Upload(short value) {
    this.conn0Upload = value;
  }

  /**
   * Gets the value of the conn0Uploadspeed property.
   *
   * @return possible object is {@link String }
   */
  public String getConn0Uploadspeed() {
    return conn0Uploadspeed;
  }

  /**
   * Sets the value of the conn0Uploadspeed property.
   *
   * @param value allowed object is {@link String }
   */
  public void setConn0Uploadspeed(String value) {
    this.conn0Uploadspeed = value;
  }

  /** Gets the value of the conn0Download property. */
  public short getConn0Download() {
    return conn0Download;
  }

  /** Sets the value of the conn0Download property. */
  public void setConn0Download(short value) {
    this.conn0Download = value;
  }

  /**
   * Gets the value of the conn0Downloadspeed property.
   *
   * @return possible object is {@link String }
   */
  public String getConn0Downloadspeed() {
    return conn0Downloadspeed;
  }

  /**
   * Sets the value of the conn0Downloadspeed property.
   *
   * @param value allowed object is {@link String }
   */
  public void setConn0Downloadspeed(String value) {
    this.conn0Downloadspeed = value;
  }

  /**
   * Gets the value of the conn0Interface property.
   *
   * @return possible object is {@link String }
   */
  public String getConn0Interface() {
    return conn0Interface;
  }

  /**
   * Sets the value of the conn0Interface property.
   *
   * @param value allowed object is {@link String }
   */
  public void setConn0Interface(String value) {
    this.conn0Interface = value;
  }
}
