//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.10.31 at 02:18:28 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}optimization"/&gt;
 *         &lt;element ref="{}hostname"/&gt;
 *         &lt;element ref="{}domain"/&gt;
 *         &lt;element ref="{}group" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}user" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}nextuid"/&gt;
 *         &lt;element ref="{}nextgid"/&gt;
 *         &lt;element ref="{}timeservers"/&gt;
 *         &lt;element ref="{}webgui"/&gt;
 *         &lt;element ref="{}disablesegmentationoffloading"/&gt;
 *         &lt;element ref="{}disablelargereceiveoffloading"/&gt;
 *         &lt;element ref="{}ipv6allow"/&gt;
 *         &lt;element ref="{}maximumtableentries"/&gt;
 *         &lt;element ref="{}powerd_ac_mode"/&gt;
 *         &lt;element ref="{}powerd_battery_mode"/&gt;
 *         &lt;element ref="{}powerd_normal_mode"/&gt;
 *         &lt;element ref="{}bogons"/&gt;
 *         &lt;element ref="{}hn_altq_enable"/&gt;
 *         &lt;element ref="{}already_run_config_upgrade"/&gt;
 *         &lt;element ref="{}ssh"/&gt;
 *         &lt;element ref="{}timezone"/&gt;
 *         &lt;element ref="{}language"/&gt;
 *         &lt;element ref="{}dns1host"/&gt;
 *         &lt;element ref="{}serialspeed"/&gt;
 *         &lt;element ref="{}primaryconsole"/&gt;
 *         &lt;element ref="{}ipv6dontcreatelocaldns"/&gt;
 *         &lt;element ref="{}prefer_ipv4"/&gt;
 *         &lt;element ref="{}pkg_repo_conf_path"/&gt;
 *         &lt;element ref="{}maximumstates"/&gt;
 *         &lt;element ref="{}aliasesresolveinterval"/&gt;
 *         &lt;element ref="{}maximumfrags"/&gt;
 *         &lt;element ref="{}enablenatreflectionpurenat"/&gt;
 *         &lt;element ref="{}reflectiontimeout"/&gt;
 *         &lt;element ref="{}consolebell"/&gt;
 *         &lt;element ref="{}dnsallowoverride"/&gt;
 *         &lt;element ref="{}earlyshellcmd"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {
      "optimization",
      "hostname",
      "domain",
      "group",
      "user",
      "nextuid",
      "nextgid",
      "timeservers",
      "webgui",
      "disablesegmentationoffloading",
      "disablelargereceiveoffloading",
      "ipv6Allow",
      "maximumtableentries",
      "powerdAcMode",
      "powerdBatteryMode",
      "powerdNormalMode",
      "bogons",
      "hnAltqEnable",
      "alreadyRunConfigUpgrade",
      "ssh",
      "timezone",
      "language",
      "dns1Host",
      "serialspeed",
      "primaryconsole",
      "ipv6Dontcreatelocaldns",
      "preferIpv4",
      "pkgRepoConfPath",
      "maximumstates",
      "aliasesresolveinterval",
      "maximumfrags",
      "enablenatreflectionpurenat",
      "reflectiontimeout",
      "consolebell",
      "dnsallowoverride",
      "earlyshellcmd"
    })
@XmlRootElement(name = "system")
public class System {

  @XmlElement(required = true)
  protected String optimization;

  @XmlElement(required = true)
  protected String hostname;

  @XmlElement(required = true)
  protected String domain;

  protected List<Group> group;
  protected List<User> user;

  @XmlElement(required = true)
  protected String nextuid;

  @XmlElement(required = true)
  protected String nextgid;

  @XmlElement(required = true)
  protected String timeservers;

  @XmlElement(required = true)
  protected Webgui webgui;

  @XmlElement(required = true)
  protected String disablesegmentationoffloading;

  @XmlElement(required = true)
  protected String disablelargereceiveoffloading;

  @XmlElement(name = "ipv6allow", required = true)
  protected String ipv6Allow;

  @XmlElement(required = true)
  protected String maximumtableentries;

  @XmlElement(name = "powerd_ac_mode", required = true)
  protected String powerdAcMode;

  @XmlElement(name = "powerd_battery_mode", required = true)
  protected String powerdBatteryMode;

  @XmlElement(name = "powerd_normal_mode", required = true)
  protected String powerdNormalMode;

  @XmlElement(required = true)
  protected Bogons bogons;

  @XmlElement(name = "hn_altq_enable", required = true)
  protected String hnAltqEnable;

  @XmlElement(name = "already_run_config_upgrade", required = true)
  protected String alreadyRunConfigUpgrade;

  @XmlElement(required = true)
  protected Ssh ssh;

  @XmlElement(required = true)
  protected String timezone;

  @XmlElement(required = true)
  protected String language;

  @XmlElement(name = "dns1host", required = true)
  protected String dns1Host;

  @XmlElement(required = true)
  protected String serialspeed;

  @XmlElement(required = true)
  protected String primaryconsole;

  @XmlElement(name = "ipv6dontcreatelocaldns", required = true)
  protected String ipv6Dontcreatelocaldns;

  @XmlElement(name = "prefer_ipv4", required = true)
  protected String preferIpv4;

  @XmlElement(name = "pkg_repo_conf_path", required = true)
  protected String pkgRepoConfPath;

  @XmlElement(required = true)
  protected String maximumstates;

  @XmlElement(required = true)
  protected String aliasesresolveinterval;

  @XmlElement(required = true)
  protected String maximumfrags;

  @XmlElement(required = true)
  protected String enablenatreflectionpurenat;

  @XmlElement(required = true)
  protected String reflectiontimeout;

  @XmlElement(required = true)
  protected String consolebell;

  @XmlElement(required = true)
  protected String dnsallowoverride;

  @XmlElement(required = true)
  protected String earlyshellcmd;

  /**
   * Gets the value of the optimization property.
   *
   * @return possible object is {@link String }
   */
  public String getOptimization() {
    return optimization;
  }

  /**
   * Sets the value of the optimization property.
   *
   * @param value allowed object is {@link String }
   */
  public void setOptimization(String value) {
    this.optimization = value;
  }

  /**
   * Gets the value of the hostname property.
   *
   * @return possible object is {@link String }
   */
  public String getHostname() {
    return hostname;
  }

  /**
   * Sets the value of the hostname property.
   *
   * @param value allowed object is {@link String }
   */
  public void setHostname(String value) {
    this.hostname = value;
  }

  /**
   * Gets the value of the domain property.
   *
   * @return possible object is {@link String }
   */
  public String getDomain() {
    return domain;
  }

  /**
   * Sets the value of the domain property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDomain(String value) {
    this.domain = value;
  }

  /**
   * Gets the value of the group property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the Jakarta XML Binding
   * object. This is why there is not a <CODE>set</CODE> method for the group property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getGroup().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Group }
   */
  public List<Group> getGroup() {
    if (group == null) {
      group = new ArrayList<Group>();
    }
    return this.group;
  }

  /**
   * Gets the value of the user property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the Jakarta XML Binding
   * object. This is why there is not a <CODE>set</CODE> method for the user property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getUser().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link User }
   */
  public List<User> getUser() {
    if (user == null) {
      user = new ArrayList<User>();
    }
    return this.user;
  }

  /**
   * Gets the value of the nextuid property.
   *
   * @return possible object is {@link String }
   */
  public String getNextuid() {
    return nextuid;
  }

  /**
   * Sets the value of the nextuid property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNextuid(String value) {
    this.nextuid = value;
  }

  /**
   * Gets the value of the nextgid property.
   *
   * @return possible object is {@link String }
   */
  public String getNextgid() {
    return nextgid;
  }

  /**
   * Sets the value of the nextgid property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNextgid(String value) {
    this.nextgid = value;
  }

  /**
   * Gets the value of the timeservers property.
   *
   * @return possible object is {@link String }
   */
  public String getTimeservers() {
    return timeservers;
  }

  /**
   * Sets the value of the timeservers property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTimeservers(String value) {
    this.timeservers = value;
  }

  /**
   * Gets the value of the webgui property.
   *
   * @return possible object is {@link Webgui }
   */
  public Webgui getWebgui() {
    return webgui;
  }

  /**
   * Sets the value of the webgui property.
   *
   * @param value allowed object is {@link Webgui }
   */
  public void setWebgui(Webgui value) {
    this.webgui = value;
  }

  /**
   * Gets the value of the disablesegmentationoffloading property.
   *
   * @return possible object is {@link String }
   */
  public String getDisablesegmentationoffloading() {
    return disablesegmentationoffloading;
  }

  /**
   * Sets the value of the disablesegmentationoffloading property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDisablesegmentationoffloading(String value) {
    this.disablesegmentationoffloading = value;
  }

  /**
   * Gets the value of the disablelargereceiveoffloading property.
   *
   * @return possible object is {@link String }
   */
  public String getDisablelargereceiveoffloading() {
    return disablelargereceiveoffloading;
  }

  /**
   * Sets the value of the disablelargereceiveoffloading property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDisablelargereceiveoffloading(String value) {
    this.disablelargereceiveoffloading = value;
  }

  /**
   * Gets the value of the ipv6Allow property.
   *
   * @return possible object is {@link String }
   */
  public String getIpv6Allow() {
    return ipv6Allow;
  }

  /**
   * Sets the value of the ipv6Allow property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIpv6Allow(String value) {
    this.ipv6Allow = value;
  }

  /**
   * Gets the value of the maximumtableentries property.
   *
   * @return possible object is {@link String }
   */
  public String getMaximumtableentries() {
    return maximumtableentries;
  }

  /**
   * Sets the value of the maximumtableentries property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMaximumtableentries(String value) {
    this.maximumtableentries = value;
  }

  /**
   * Gets the value of the powerdAcMode property.
   *
   * @return possible object is {@link String }
   */
  public String getPowerdAcMode() {
    return powerdAcMode;
  }

  /**
   * Sets the value of the powerdAcMode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPowerdAcMode(String value) {
    this.powerdAcMode = value;
  }

  /**
   * Gets the value of the powerdBatteryMode property.
   *
   * @return possible object is {@link String }
   */
  public String getPowerdBatteryMode() {
    return powerdBatteryMode;
  }

  /**
   * Sets the value of the powerdBatteryMode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPowerdBatteryMode(String value) {
    this.powerdBatteryMode = value;
  }

  /**
   * Gets the value of the powerdNormalMode property.
   *
   * @return possible object is {@link String }
   */
  public String getPowerdNormalMode() {
    return powerdNormalMode;
  }

  /**
   * Sets the value of the powerdNormalMode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPowerdNormalMode(String value) {
    this.powerdNormalMode = value;
  }

  /**
   * Gets the value of the bogons property.
   *
   * @return possible object is {@link Bogons }
   */
  public Bogons getBogons() {
    return bogons;
  }

  /**
   * Sets the value of the bogons property.
   *
   * @param value allowed object is {@link Bogons }
   */
  public void setBogons(Bogons value) {
    this.bogons = value;
  }

  /**
   * Gets the value of the hnAltqEnable property.
   *
   * @return possible object is {@link String }
   */
  public String getHnAltqEnable() {
    return hnAltqEnable;
  }

  /**
   * Sets the value of the hnAltqEnable property.
   *
   * @param value allowed object is {@link String }
   */
  public void setHnAltqEnable(String value) {
    this.hnAltqEnable = value;
  }

  /**
   * Gets the value of the alreadyRunConfigUpgrade property.
   *
   * @return possible object is {@link String }
   */
  public String getAlreadyRunConfigUpgrade() {
    return alreadyRunConfigUpgrade;
  }

  /**
   * Sets the value of the alreadyRunConfigUpgrade property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAlreadyRunConfigUpgrade(String value) {
    this.alreadyRunConfigUpgrade = value;
  }

  /**
   * Gets the value of the ssh property.
   *
   * @return possible object is {@link Ssh }
   */
  public Ssh getSsh() {
    return ssh;
  }

  /**
   * Sets the value of the ssh property.
   *
   * @param value allowed object is {@link Ssh }
   */
  public void setSsh(Ssh value) {
    this.ssh = value;
  }

  /**
   * Gets the value of the timezone property.
   *
   * @return possible object is {@link String }
   */
  public String getTimezone() {
    return timezone;
  }

  /**
   * Sets the value of the timezone property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTimezone(String value) {
    this.timezone = value;
  }

  /**
   * Gets the value of the language property.
   *
   * @return possible object is {@link String }
   */
  public String getLanguage() {
    return language;
  }

  /**
   * Sets the value of the language property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLanguage(String value) {
    this.language = value;
  }

  /**
   * Gets the value of the dns1Host property.
   *
   * @return possible object is {@link String }
   */
  public String getDns1Host() {
    return dns1Host;
  }

  /**
   * Sets the value of the dns1Host property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDns1Host(String value) {
    this.dns1Host = value;
  }

  /**
   * Gets the value of the serialspeed property.
   *
   * @return possible object is {@link String }
   */
  public String getSerialspeed() {
    return serialspeed;
  }

  /**
   * Sets the value of the serialspeed property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSerialspeed(String value) {
    this.serialspeed = value;
  }

  /**
   * Gets the value of the primaryconsole property.
   *
   * @return possible object is {@link String }
   */
  public String getPrimaryconsole() {
    return primaryconsole;
  }

  /**
   * Sets the value of the primaryconsole property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPrimaryconsole(String value) {
    this.primaryconsole = value;
  }

  /**
   * Gets the value of the ipv6Dontcreatelocaldns property.
   *
   * @return possible object is {@link String }
   */
  public String getIpv6Dontcreatelocaldns() {
    return ipv6Dontcreatelocaldns;
  }

  /**
   * Sets the value of the ipv6Dontcreatelocaldns property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIpv6Dontcreatelocaldns(String value) {
    this.ipv6Dontcreatelocaldns = value;
  }

  /**
   * Gets the value of the preferIpv4 property.
   *
   * @return possible object is {@link String }
   */
  public String getPreferIpv4() {
    return preferIpv4;
  }

  /**
   * Sets the value of the preferIpv4 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPreferIpv4(String value) {
    this.preferIpv4 = value;
  }

  /**
   * Gets the value of the pkgRepoConfPath property.
   *
   * @return possible object is {@link String }
   */
  public String getPkgRepoConfPath() {
    return pkgRepoConfPath;
  }

  /**
   * Sets the value of the pkgRepoConfPath property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPkgRepoConfPath(String value) {
    this.pkgRepoConfPath = value;
  }

  /**
   * Gets the value of the maximumstates property.
   *
   * @return possible object is {@link String }
   */
  public String getMaximumstates() {
    return maximumstates;
  }

  /**
   * Sets the value of the maximumstates property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMaximumstates(String value) {
    this.maximumstates = value;
  }

  /**
   * Gets the value of the aliasesresolveinterval property.
   *
   * @return possible object is {@link String }
   */
  public String getAliasesresolveinterval() {
    return aliasesresolveinterval;
  }

  /**
   * Sets the value of the aliasesresolveinterval property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAliasesresolveinterval(String value) {
    this.aliasesresolveinterval = value;
  }

  /**
   * Gets the value of the maximumfrags property.
   *
   * @return possible object is {@link String }
   */
  public String getMaximumfrags() {
    return maximumfrags;
  }

  /**
   * Sets the value of the maximumfrags property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMaximumfrags(String value) {
    this.maximumfrags = value;
  }

  /**
   * Gets the value of the enablenatreflectionpurenat property.
   *
   * @return possible object is {@link String }
   */
  public String getEnablenatreflectionpurenat() {
    return enablenatreflectionpurenat;
  }

  /**
   * Sets the value of the enablenatreflectionpurenat property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEnablenatreflectionpurenat(String value) {
    this.enablenatreflectionpurenat = value;
  }

  /**
   * Gets the value of the reflectiontimeout property.
   *
   * @return possible object is {@link String }
   */
  public String getReflectiontimeout() {
    return reflectiontimeout;
  }

  /**
   * Sets the value of the reflectiontimeout property.
   *
   * @param value allowed object is {@link String }
   */
  public void setReflectiontimeout(String value) {
    this.reflectiontimeout = value;
  }

  /**
   * Gets the value of the consolebell property.
   *
   * @return possible object is {@link String }
   */
  public String getConsolebell() {
    return consolebell;
  }

  /**
   * Sets the value of the consolebell property.
   *
   * @param value allowed object is {@link String }
   */
  public void setConsolebell(String value) {
    this.consolebell = value;
  }

  /**
   * Gets the value of the dnsallowoverride property.
   *
   * @return possible object is {@link String }
   */
  public String getDnsallowoverride() {
    return dnsallowoverride;
  }

  /**
   * Sets the value of the dnsallowoverride property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDnsallowoverride(String value) {
    this.dnsallowoverride = value;
  }

  /**
   * Gets the value of the earlyshellcmd property.
   *
   * @return possible object is {@link String }
   */
  public String getEarlyshellcmd() {
    return earlyshellcmd;
  }

  /**
   * Sets the value of the earlyshellcmd property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEarlyshellcmd(String value) {
    this.earlyshellcmd = value;
  }
}
