//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for traffic_graphsType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="traffic_graphsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="refreshinterval" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="invert" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="backgroundupdate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="smoothfactor" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="filter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="if" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sort" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="hostipformat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "traffic_graphsType",
    propOrder = {"refreshintervalOrInvertOrBackgroundupdate"})
public class TrafficGraphsType {

  @XmlElementRefs({
    @XmlElementRef(name = "refreshinterval", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "invert", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "backgroundupdate", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "smoothfactor", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "size", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "filter", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "if", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "sort", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "hostipformat", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "mode", type = JAXBElement.class, required = false)
  })
  protected List<JAXBElement<? extends Serializable>> refreshintervalOrInvertOrBackgroundupdate;

  /**
   * Gets the value of the refreshintervalOrInvertOrBackgroundupdate property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the Jakarta XML Binding
   * object. This is why there is not a <CODE>set</CODE> method for the
   * refreshintervalOrInvertOrBackgroundupdate property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getRefreshintervalOrInvertOrBackgroundupdate().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link
   * Byte }{@code >} {@link JAXBElement }{@code <}{@link Byte }{@code >} {@link JAXBElement }{@code
   * <}{@link Byte }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String
   * }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code
   * <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >}
   */
  public List<JAXBElement<? extends Serializable>> getRefreshintervalOrInvertOrBackgroundupdate() {
    if (refreshintervalOrInvertOrBackgroundupdate == null) {
      refreshintervalOrInvertOrBackgroundupdate =
          new ArrayList<JAXBElement<? extends Serializable>>();
    }
    return this.refreshintervalOrInvertOrBackgroundupdate;
  }
}
