//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.10.31 at 02:18:28 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}dnssec"/&gt;
 *         &lt;element ref="{}active_interface"/&gt;
 *         &lt;element ref="{}outgoing_interface"/&gt;
 *         &lt;element ref="{}custom_options"/&gt;
 *         &lt;element ref="{}hideidentity"/&gt;
 *         &lt;element ref="{}hideversion"/&gt;
 *         &lt;element ref="{}dnssecstripped"/&gt;
 *         &lt;element ref="{}port"/&gt;
 *         &lt;element ref="{}tlsport"/&gt;
 *         &lt;element ref="{}sslcertref"/&gt;
 *         &lt;element ref="{}system_domain_local_zone_type"/&gt;
 *         &lt;element ref="{}acls"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {
      "dnssec",
      "activeInterface",
      "outgoingInterface",
      "customOptions",
      "hideidentity",
      "hideversion",
      "dnssecstripped",
      "port",
      "tlsport",
      "sslcertref",
      "systemDomainLocalZoneType",
      "acls"
    })
@XmlRootElement(name = "unbound")
public class Unbound {

  @XmlElement(required = true)
  protected String dnssec;

  @XmlElement(name = "active_interface", required = true)
  protected String activeInterface;

  @XmlElement(name = "outgoing_interface", required = true)
  protected String outgoingInterface;

  @XmlElement(name = "custom_options", required = true)
  protected String customOptions;

  @XmlElement(required = true)
  protected String hideidentity;

  @XmlElement(required = true)
  protected String hideversion;

  @XmlElement(required = true)
  protected String dnssecstripped;

  @XmlElement(required = true)
  protected String port;

  @XmlElement(required = true)
  protected String tlsport;

  @XmlElement(required = true)
  protected String sslcertref;

  @XmlElement(name = "system_domain_local_zone_type", required = true)
  protected String systemDomainLocalZoneType;

  @XmlElement(required = true)
  protected Acls acls;

  /**
   * Gets the value of the dnssec property.
   *
   * @return possible object is {@link String }
   */
  public String getDnssec() {
    return dnssec;
  }

  /**
   * Sets the value of the dnssec property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDnssec(String value) {
    this.dnssec = value;
  }

  /**
   * Gets the value of the activeInterface property.
   *
   * @return possible object is {@link String }
   */
  public String getActiveInterface() {
    return activeInterface;
  }

  /**
   * Sets the value of the activeInterface property.
   *
   * @param value allowed object is {@link String }
   */
  public void setActiveInterface(String value) {
    this.activeInterface = value;
  }

  /**
   * Gets the value of the outgoingInterface property.
   *
   * @return possible object is {@link String }
   */
  public String getOutgoingInterface() {
    return outgoingInterface;
  }

  /**
   * Sets the value of the outgoingInterface property.
   *
   * @param value allowed object is {@link String }
   */
  public void setOutgoingInterface(String value) {
    this.outgoingInterface = value;
  }

  /**
   * Gets the value of the customOptions property.
   *
   * @return possible object is {@link String }
   */
  public String getCustomOptions() {
    return customOptions;
  }

  /**
   * Sets the value of the customOptions property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCustomOptions(String value) {
    this.customOptions = value;
  }

  /**
   * Gets the value of the hideidentity property.
   *
   * @return possible object is {@link String }
   */
  public String getHideidentity() {
    return hideidentity;
  }

  /**
   * Sets the value of the hideidentity property.
   *
   * @param value allowed object is {@link String }
   */
  public void setHideidentity(String value) {
    this.hideidentity = value;
  }

  /**
   * Gets the value of the hideversion property.
   *
   * @return possible object is {@link String }
   */
  public String getHideversion() {
    return hideversion;
  }

  /**
   * Sets the value of the hideversion property.
   *
   * @param value allowed object is {@link String }
   */
  public void setHideversion(String value) {
    this.hideversion = value;
  }

  /**
   * Gets the value of the dnssecstripped property.
   *
   * @return possible object is {@link String }
   */
  public String getDnssecstripped() {
    return dnssecstripped;
  }

  /**
   * Sets the value of the dnssecstripped property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDnssecstripped(String value) {
    this.dnssecstripped = value;
  }

  /**
   * Gets the value of the port property.
   *
   * @return possible object is {@link String }
   */
  public String getPort() {
    return port;
  }

  /**
   * Sets the value of the port property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPort(String value) {
    this.port = value;
  }

  /**
   * Gets the value of the tlsport property.
   *
   * @return possible object is {@link String }
   */
  public String getTlsport() {
    return tlsport;
  }

  /**
   * Sets the value of the tlsport property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTlsport(String value) {
    this.tlsport = value;
  }

  /**
   * Gets the value of the sslcertref property.
   *
   * @return possible object is {@link String }
   */
  public String getSslcertref() {
    return sslcertref;
  }

  /**
   * Sets the value of the sslcertref property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSslcertref(String value) {
    this.sslcertref = value;
  }

  /**
   * Gets the value of the systemDomainLocalZoneType property.
   *
   * @return possible object is {@link String }
   */
  public String getSystemDomainLocalZoneType() {
    return systemDomainLocalZoneType;
  }

  /**
   * Sets the value of the systemDomainLocalZoneType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSystemDomainLocalZoneType(String value) {
    this.systemDomainLocalZoneType = value;
  }

  /**
   * Gets the value of the acls property.
   *
   * @return possible object is {@link Acls }
   */
  public Acls getAcls() {
    return acls;
  }

  /**
   * Sets the value of the acls property.
   *
   * @param value allowed object is {@link Acls }
   */
  public void setAcls(Acls value) {
    this.acls = value;
  }
}
