//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for userType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="userType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="scope" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bcrypt-hash" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="descr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="expires" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dashboardcolumns" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="authorizedkeys" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ipsecpsk" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webguicss" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="priv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="groupname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "userType",
    propOrder = {"scopeOrBcryptHashOrDescr"})
public class UserType {

  @XmlElementRefs({
    @XmlElementRef(name = "scope", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "bcrypt-hash", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "descr", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "expires", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "dashboardcolumns", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "authorizedkeys", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "ipsecpsk", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "webguicss", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "uid", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "priv", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "groupname", type = JAXBElement.class, required = false)
  })
  protected List<JAXBElement<? extends Serializable>> scopeOrBcryptHashOrDescr;

  /**
   * Gets the value of the scopeOrBcryptHashOrDescr property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the Jakarta XML Binding
   * object. This is why there is not a <CODE>set</CODE> method for the scopeOrBcryptHashOrDescr
   * property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getScopeOrBcryptHashOrDescr().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link
   * Byte }{@code >} {@link JAXBElement }{@code <}{@link Short }{@code >} {@link JAXBElement }{@code
   * <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String
   * }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code
   * <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String
   * }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >}
   */
  public List<JAXBElement<? extends Serializable>> getScopeOrBcryptHashOrDescr() {
    if (scopeOrBcryptHashOrDescr == null) {
      scopeOrBcryptHashOrDescr = new ArrayList<JAXBElement<? extends Serializable>>();
    }
    return this.scopeOrBcryptHashOrDescr;
  }
}
