//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import eu.ad4ubg.adapters.CDATAAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Java class for wanType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="wanType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="enable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="if" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="descr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="alias-address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="alias-subnet" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/&gt;
 *         &lt;element name="spoofmac" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ipaddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dhcphostname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dhcprejectfrom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_pt_timeout" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_pt_retry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_pt_select_timeout" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_pt_reboot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_pt_backoff_cutoff" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_pt_initial_interval" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_pt_values" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_send_options" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_request_options" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_required_options" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_option_modifiers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_config_advanced" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_config_file_override" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adv_dhcp_config_file_override_path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sep0" type="{}sep0Type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "wanType",
    propOrder = {
      "enable",
      "_if",
      "descr",
      "aliasAddress",
      "aliasSubnet",
      "spoofmac",
      "ipaddr",
      "dhcphostname",
      "dhcprejectfrom",
      "advDhcpPtTimeout",
      "advDhcpPtRetry",
      "advDhcpPtSelectTimeout",
      "advDhcpPtReboot",
      "advDhcpPtBackoffCutoff",
      "advDhcpPtInitialInterval",
      "advDhcpPtValues",
      "advDhcpSendOptions",
      "advDhcpRequestOptions",
      "advDhcpRequiredOptions",
      "advDhcpOptionModifiers",
      "advDhcpConfigAdvanced",
      "advDhcpConfigFileOverride",
      "advDhcpConfigFileOverridePath",
      "sep0"
    })
public class WanType {

  protected String enable;

  @XmlElement(name = "if")
  protected String _if;

  @XmlJavaTypeAdapter(CDATAAdapter.class)
  protected String descr;

  @XmlElement(name = "alias-address")
  protected String aliasAddress;

  @XmlElement(name = "alias-subnet")
  protected Byte aliasSubnet;

  protected String spoofmac;
  protected String ipaddr;
  protected String dhcphostname;
  protected String dhcprejectfrom;

  @XmlElement(name = "adv_dhcp_pt_timeout")
  protected String advDhcpPtTimeout;

  @XmlElement(name = "adv_dhcp_pt_retry")
  protected String advDhcpPtRetry;

  @XmlElement(name = "adv_dhcp_pt_select_timeout")
  protected String advDhcpPtSelectTimeout;

  @XmlElement(name = "adv_dhcp_pt_reboot")
  protected String advDhcpPtReboot;

  @XmlElement(name = "adv_dhcp_pt_backoff_cutoff")
  protected String advDhcpPtBackoffCutoff;

  @XmlElement(name = "adv_dhcp_pt_initial_interval")
  protected String advDhcpPtInitialInterval;

  @XmlElement(name = "adv_dhcp_pt_values")
  protected String advDhcpPtValues;

  @XmlElement(name = "adv_dhcp_send_options")
  protected String advDhcpSendOptions;

  @XmlElement(name = "adv_dhcp_request_options")
  protected String advDhcpRequestOptions;

  @XmlElement(name = "adv_dhcp_required_options")
  protected String advDhcpRequiredOptions;

  @XmlElement(name = "adv_dhcp_option_modifiers")
  protected String advDhcpOptionModifiers;

  @XmlElement(name = "adv_dhcp_config_advanced")
  protected String advDhcpConfigAdvanced;

  @XmlElement(name = "adv_dhcp_config_file_override")
  protected String advDhcpConfigFileOverride;

  @XmlElement(name = "adv_dhcp_config_file_override_path")
  protected String advDhcpConfigFileOverridePath;

  protected Sep0Type sep0;

  /**
   * Gets the value of the enable property.
   *
   * @return possible object is {@link String }
   */
  public String getEnable() {
    return enable;
  }

  /**
   * Sets the value of the enable property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEnable(String value) {
    this.enable = value;
  }

  /**
   * Gets the value of the if property.
   *
   * @return possible object is {@link String }
   */
  public String getIf() {
    return _if;
  }

  /**
   * Sets the value of the if property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIf(String value) {
    this._if = value;
  }

  /**
   * Gets the value of the descr property.
   *
   * @return possible object is {@link String }
   */
  public String getDescr() {
    return descr;
  }

  /**
   * Sets the value of the descr property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescr(String value) {
    this.descr = value;
  }

  /**
   * Gets the value of the aliasAddress property.
   *
   * @return possible object is {@link String }
   */
  public String getAliasAddress() {
    return aliasAddress;
  }

  /**
   * Sets the value of the aliasAddress property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAliasAddress(String value) {
    this.aliasAddress = value;
  }

  /**
   * Gets the value of the aliasSubnet property.
   *
   * @return possible object is {@link Byte }
   */
  public Byte getAliasSubnet() {
    return aliasSubnet;
  }

  /**
   * Sets the value of the aliasSubnet property.
   *
   * @param value allowed object is {@link Byte }
   */
  public void setAliasSubnet(Byte value) {
    this.aliasSubnet = value;
  }

  /**
   * Gets the value of the spoofmac property.
   *
   * @return possible object is {@link String }
   */
  public String getSpoofmac() {
    return spoofmac;
  }

  /**
   * Sets the value of the spoofmac property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSpoofmac(String value) {
    this.spoofmac = value;
  }

  /**
   * Gets the value of the ipaddr property.
   *
   * @return possible object is {@link String }
   */
  public String getIpaddr() {
    return ipaddr;
  }

  /**
   * Sets the value of the ipaddr property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIpaddr(String value) {
    this.ipaddr = value;
  }

  /**
   * Gets the value of the dhcphostname property.
   *
   * @return possible object is {@link String }
   */
  public String getDhcphostname() {
    return dhcphostname;
  }

  /**
   * Sets the value of the dhcphostname property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDhcphostname(String value) {
    this.dhcphostname = value;
  }

  /**
   * Gets the value of the dhcprejectfrom property.
   *
   * @return possible object is {@link String }
   */
  public String getDhcprejectfrom() {
    return dhcprejectfrom;
  }

  /**
   * Sets the value of the dhcprejectfrom property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDhcprejectfrom(String value) {
    this.dhcprejectfrom = value;
  }

  /**
   * Gets the value of the advDhcpPtTimeout property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpPtTimeout() {
    return advDhcpPtTimeout;
  }

  /**
   * Sets the value of the advDhcpPtTimeout property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpPtTimeout(String value) {
    this.advDhcpPtTimeout = value;
  }

  /**
   * Gets the value of the advDhcpPtRetry property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpPtRetry() {
    return advDhcpPtRetry;
  }

  /**
   * Sets the value of the advDhcpPtRetry property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpPtRetry(String value) {
    this.advDhcpPtRetry = value;
  }

  /**
   * Gets the value of the advDhcpPtSelectTimeout property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpPtSelectTimeout() {
    return advDhcpPtSelectTimeout;
  }

  /**
   * Sets the value of the advDhcpPtSelectTimeout property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpPtSelectTimeout(String value) {
    this.advDhcpPtSelectTimeout = value;
  }

  /**
   * Gets the value of the advDhcpPtReboot property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpPtReboot() {
    return advDhcpPtReboot;
  }

  /**
   * Sets the value of the advDhcpPtReboot property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpPtReboot(String value) {
    this.advDhcpPtReboot = value;
  }

  /**
   * Gets the value of the advDhcpPtBackoffCutoff property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpPtBackoffCutoff() {
    return advDhcpPtBackoffCutoff;
  }

  /**
   * Sets the value of the advDhcpPtBackoffCutoff property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpPtBackoffCutoff(String value) {
    this.advDhcpPtBackoffCutoff = value;
  }

  /**
   * Gets the value of the advDhcpPtInitialInterval property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpPtInitialInterval() {
    return advDhcpPtInitialInterval;
  }

  /**
   * Sets the value of the advDhcpPtInitialInterval property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpPtInitialInterval(String value) {
    this.advDhcpPtInitialInterval = value;
  }

  /**
   * Gets the value of the advDhcpPtValues property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpPtValues() {
    return advDhcpPtValues;
  }

  /**
   * Sets the value of the advDhcpPtValues property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpPtValues(String value) {
    this.advDhcpPtValues = value;
  }

  /**
   * Gets the value of the advDhcpSendOptions property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpSendOptions() {
    return advDhcpSendOptions;
  }

  /**
   * Sets the value of the advDhcpSendOptions property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpSendOptions(String value) {
    this.advDhcpSendOptions = value;
  }

  /**
   * Gets the value of the advDhcpRequestOptions property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpRequestOptions() {
    return advDhcpRequestOptions;
  }

  /**
   * Sets the value of the advDhcpRequestOptions property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpRequestOptions(String value) {
    this.advDhcpRequestOptions = value;
  }

  /**
   * Gets the value of the advDhcpRequiredOptions property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpRequiredOptions() {
    return advDhcpRequiredOptions;
  }

  /**
   * Sets the value of the advDhcpRequiredOptions property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpRequiredOptions(String value) {
    this.advDhcpRequiredOptions = value;
  }

  /**
   * Gets the value of the advDhcpOptionModifiers property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpOptionModifiers() {
    return advDhcpOptionModifiers;
  }

  /**
   * Sets the value of the advDhcpOptionModifiers property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpOptionModifiers(String value) {
    this.advDhcpOptionModifiers = value;
  }

  /**
   * Gets the value of the advDhcpConfigAdvanced property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpConfigAdvanced() {
    return advDhcpConfigAdvanced;
  }

  /**
   * Sets the value of the advDhcpConfigAdvanced property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpConfigAdvanced(String value) {
    this.advDhcpConfigAdvanced = value;
  }

  /**
   * Gets the value of the advDhcpConfigFileOverride property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpConfigFileOverride() {
    return advDhcpConfigFileOverride;
  }

  /**
   * Sets the value of the advDhcpConfigFileOverride property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpConfigFileOverride(String value) {
    this.advDhcpConfigFileOverride = value;
  }

  /**
   * Gets the value of the advDhcpConfigFileOverridePath property.
   *
   * @return possible object is {@link String }
   */
  public String getAdvDhcpConfigFileOverridePath() {
    return advDhcpConfigFileOverridePath;
  }

  /**
   * Sets the value of the advDhcpConfigFileOverridePath property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdvDhcpConfigFileOverridePath(String value) {
    this.advDhcpConfigFileOverridePath = value;
  }

  /**
   * Gets the value of the sep0 property.
   *
   * @return possible object is {@link Sep0Type }
   */
  public Sep0Type getSep0() {
    return sep0;
  }

  /**
   * Sets the value of the sep0 property.
   *
   * @param value allowed object is {@link Sep0Type }
   */
  public void setSep0(Sep0Type value) {
    this.sep0 = value;
  }
}
