//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.03.29 at 01:34:01 PM EET
//

package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for widgetsType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="widgetsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sequence" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="traffic_graphs" type="{}traffic_graphsType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "widgetsType",
    propOrder = {"sequence", "period", "trafficGraphs"})
public class WidgetsType {

  @XmlElement(required = true)
  protected String sequence;

  protected byte period;

  @XmlElement(name = "traffic_graphs", required = true)
  protected TrafficGraphsType trafficGraphs;

  /**
   * Gets the value of the sequence property.
   *
   * @return possible object is {@link String }
   */
  public String getSequence() {
    return sequence;
  }

  /**
   * Sets the value of the sequence property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSequence(String value) {
    this.sequence = value;
  }

  /** Gets the value of the period property. */
  public byte getPeriod() {
    return period;
  }

  /** Sets the value of the period property. */
  public void setPeriod(byte value) {
    this.period = value;
  }

  /**
   * Gets the value of the trafficGraphs property.
   *
   * @return possible object is {@link TrafficGraphsType }
   */
  public TrafficGraphsType getTrafficGraphs() {
    return trafficGraphs;
  }

  /**
   * Sets the value of the trafficGraphs property.
   *
   * @param value allowed object is {@link TrafficGraphsType }
   */
  public void setTrafficGraphs(TrafficGraphsType value) {
    this.trafficGraphs = value;
  }
}
