//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.12 at 10:41:00 PM EEST 
//


package eu.ad4ubg;

import java.util.ArrayList;
import java.util.List;
import eu.ad4ubg.adapters.CDATAAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}aclname"/&gt;
 *         &lt;element ref="{}aclaction"/&gt;
 *         &lt;element ref="{}description"/&gt;
 *         &lt;element ref="{}aclid"/&gt;
 *         &lt;element ref="{}row" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aclname",
    "aclaction",
    "description",
    "aclid",
    "row"
})
@XmlRootElement(name = "acls")
public class Acls {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CDATAAdapter.class)
    protected String aclname;
    @XmlElement(required = true)
    protected String aclaction;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CDATAAdapter.class)
    protected String description;
    protected byte aclid;
    @XmlElement(required = true)
    protected List<Row> row;

    /**
     * Gets the value of the aclname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAclname() {
        return aclname;
    }

    /**
     * Sets the value of the aclname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAclname(String value) {
        this.aclname = value;
    }

    /**
     * Gets the value of the aclaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAclaction() {
        return aclaction;
    }

    /**
     * Sets the value of the aclaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAclaction(String value) {
        this.aclaction = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the aclid property.
     * 
     */
    public byte getAclid() {
        return aclid;
    }

    /**
     * Sets the value of the aclid property.
     * 
     */
    public void setAclid(byte value) {
        this.aclid = value;
    }

    /**
     * Gets the value of the row property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the row property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Row }
     * 
     * 
     */
    public List<Row> getRow() {
        if (row == null) {
            row = new ArrayList<Row>();
        }
        return this.row;
    }

}
