//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.04.12 at 10:41:00 PM EEST
//

package eu.ad4ubg;

import eu.ad4ubg.adapters.CDATAAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}domain"/&gt;
 *         &lt;element ref="{}ip"/&gt;
 *         &lt;element ref="{}descr"/&gt;
 *         &lt;element ref="{}tls_hostname"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"domain", "ip", "descr", "tlsHostname"})
@XmlRootElement(name = "domainoverrides")
public class Domainoverrides {

  @XmlElement(required = true)
  protected String domain;

  @XmlElement(required = true)
  protected String ip;

  @XmlElement(required = true)
  @XmlJavaTypeAdapter(CDATAAdapter.class)
  protected String descr;

  @XmlElement(name = "tls_hostname", required = true)
  protected String tlsHostname;

  /**
   * Gets the value of the domain property.
   *
   * @return possible object is {@link String }
   */
  public String getDomain() {
    return domain;
  }

  /**
   * Sets the value of the domain property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDomain(String value) {
    this.domain = value;
  }

  /**
   * Gets the value of the ip property.
   *
   * @return possible object is {@link String }
   */
  public String getIp() {
    return ip;
  }

  /**
   * Sets the value of the ip property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIp(String value) {
    this.ip = value;
  }

  /**
   * Gets the value of the descr property.
   *
   * @return possible object is {@link String }
   */
  public String getDescr() {
    return descr;
  }

  /**
   * Sets the value of the descr property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescr(String value) {
    this.descr = value;
  }

  /**
   * Gets the value of the tlsHostname property.
   *
   * @return possible object is {@link String }
   */
  public String getTlsHostname() {
    return tlsHostname;
  }

  /**
   * Sets the value of the tlsHostname property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTlsHostname(String value) {
    this.tlsHostname = value;
  }
}
