//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.04.12 at 10:41:00 PM EEST
//

package eu.ad4ubg;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}interface"/&gt;
 *         &lt;element ref="{}gateway"/&gt;
 *         &lt;element ref="{}name"/&gt;
 *         &lt;element ref="{}weight"/&gt;
 *         &lt;element ref="{}ipprotocol"/&gt;
 *         &lt;element ref="{}descr"/&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{}monitor_disable"/&gt;
 *             &lt;element ref="{}action_disable" minOccurs="0"/&gt;
 *             &lt;element ref="{}gw_down_kill_states"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{}gw_down_kill_states"/&gt;
 *             &lt;element ref="{}monitor"/&gt;
 *           &lt;/sequence&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"content"})
@XmlRootElement(name = "gateway_item")
public class GatewayItem {

  @XmlElementRefs({
    @XmlElementRef(name = "interface", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "gateway", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "weight", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "ipprotocol", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "descr", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "monitor_disable", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "action_disable", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "gw_down_kill_states", type = JAXBElement.class, required = false),
    @XmlElementRef(name = "monitor", type = JAXBElement.class, required = false)
  })
  protected List<JAXBElement<? extends Serializable>> content;

  /**
   * Gets the rest of the content model.
   *
   * <p>You are getting this "catch-all" property because of the following reason: The field name
   * "GwDownKillStates" is used by two different parts of a schema. See: line 2308 of
   * file:/opt/workspace/java-tools/pfsense/src/main/dtd/pfsense.xsd line 2305 of
   * file:/opt/workspace/java-tools/pfsense/src/main/dtd/pfsense.xsd
   *
   * <p>To get rid of this property, apply a property customization to one of both of the following
   * declarations to change their names: Gets the value of the content property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the Jakarta XML Binding
   * object. This is why there is not a <CODE>set</CODE> method for the content property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getContent().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link
   * Byte }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement
   * }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String
   * }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }{@code
   * <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }{@code >} {@link
   * JAXBElement }{@code <}{@link String }{@code >}
   */
  public List<JAXBElement<? extends Serializable>> getContent() {
    if (content == null) {
      content = new ArrayList<JAXBElement<? extends Serializable>>();
    }
    return this.content;
  }
}
