//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.12 at 10:41:00 PM EEST 
//


package eu.ad4ubg;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{}type"/&gt;
 *           &lt;choice&gt;
 *             &lt;sequence&gt;
 *               &lt;element ref="{}ipprotocol"/&gt;
 *               &lt;element ref="{}descr"/&gt;
 *               &lt;element ref="{}interface"/&gt;
 *               &lt;element ref="{}tracker"/&gt;
 *               &lt;element ref="{}source"/&gt;
 *               &lt;element ref="{}destination"/&gt;
 *             &lt;/sequence&gt;
 *             &lt;sequence&gt;
 *               &lt;element ref="{}interface"/&gt;
 *               &lt;element ref="{}ipprotocol"/&gt;
 *               &lt;element ref="{}defaultqueue"/&gt;
 *               &lt;element ref="{}source"/&gt;
 *               &lt;element ref="{}destination"/&gt;
 *               &lt;element ref="{}floating"/&gt;
 *               &lt;element ref="{}wizard"/&gt;
 *               &lt;element ref="{}enabled"/&gt;
 *               &lt;element ref="{}descr"/&gt;
 *               &lt;element ref="{}protocol"/&gt;
 *               &lt;element ref="{}created"/&gt;
 *               &lt;element ref="{}tracker"/&gt;
 *               &lt;element ref="{}disabled"/&gt;
 *             &lt;/sequence&gt;
 *           &lt;/choice&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{}source"/&gt;
 *           &lt;element ref="{}sourceport"/&gt;
 *           &lt;element ref="{}descr"/&gt;
 *           &lt;element ref="{}target"/&gt;
 *           &lt;element ref="{}target_subnet"/&gt;
 *           &lt;element ref="{}interface"/&gt;
 *           &lt;element ref="{}poolopts"/&gt;
 *           &lt;element ref="{}source_hash_key"/&gt;
 *           &lt;choice&gt;
 *             &lt;sequence&gt;
 *               &lt;element ref="{}staticnatport"/&gt;
 *               &lt;choice&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{}ipprotocol"/&gt;
 *                   &lt;element ref="{}destination"/&gt;
 *                   &lt;element ref="{}dstport"/&gt;
 *                   &lt;choice&gt;
 *                     &lt;sequence&gt;
 *                       &lt;element ref="{}updated"/&gt;
 *                       &lt;element ref="{}created"/&gt;
 *                     &lt;/sequence&gt;
 *                     &lt;sequence&gt;
 *                       &lt;element ref="{}created"/&gt;
 *                       &lt;element ref="{}updated"/&gt;
 *                     &lt;/sequence&gt;
 *                   &lt;/choice&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{}destination"/&gt;
 *                   &lt;element ref="{}dstport"/&gt;
 *                   &lt;element ref="{}created"/&gt;
 *                   &lt;element ref="{}updated"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/choice&gt;
 *             &lt;/sequence&gt;
 *             &lt;sequence&gt;
 *               &lt;element ref="{}destination"/&gt;
 *               &lt;choice&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{}updated"/&gt;
 *                   &lt;element ref="{}created"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{}created"/&gt;
 *                   &lt;element ref="{}updated"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/choice&gt;
 *             &lt;/sequence&gt;
 *           &lt;/choice&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{}ipprotocol"/&gt;
 *           &lt;element ref="{}type"/&gt;
 *           &lt;element ref="{}descr"/&gt;
 *           &lt;element ref="{}source"/&gt;
 *           &lt;element ref="{}destination"/&gt;
 *           &lt;element ref="{}log"/&gt;
 *           &lt;element ref="{}created"/&gt;
 *           &lt;element ref="{}interface"/&gt;
 *           &lt;element ref="{}tracker"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{}interface"/&gt;
 *           &lt;element ref="{}source"/&gt;
 *           &lt;choice&gt;
 *             &lt;sequence&gt;
 *               &lt;element ref="{}sourceport"/&gt;
 *               &lt;element ref="{}target"/&gt;
 *               &lt;element ref="{}destination"/&gt;
 *               &lt;element ref="{}natport"/&gt;
 *             &lt;/sequence&gt;
 *             &lt;sequence&gt;
 *               &lt;element ref="{}dstport"/&gt;
 *               &lt;element ref="{}target"/&gt;
 *               &lt;element ref="{}destination"/&gt;
 *               &lt;element ref="{}staticnatport"/&gt;
 *             &lt;/sequence&gt;
 *           &lt;/choice&gt;
 *           &lt;element ref="{}descr"/&gt;
 *           &lt;element ref="{}created"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{}id"/&gt;
 *           &lt;element ref="{}tracker"/&gt;
 *           &lt;element ref="{}type"/&gt;
 *           &lt;element ref="{}interface"/&gt;
 *           &lt;element ref="{}ipprotocol"/&gt;
 *           &lt;element ref="{}tag"/&gt;
 *           &lt;element ref="{}tagged"/&gt;
 *           &lt;choice&gt;
 *             &lt;sequence&gt;
 *               &lt;element ref="{}max"/&gt;
 *               &lt;element ref="{}max-src-nodes"/&gt;
 *               &lt;element ref="{}max-src-conn"/&gt;
 *               &lt;element ref="{}max-src-states"/&gt;
 *               &lt;element ref="{}statetimeout"/&gt;
 *               &lt;element ref="{}statetype"/&gt;
 *               &lt;element ref="{}os"/&gt;
 *               &lt;choice&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{}source"/&gt;
 *                   &lt;element ref="{}destination"/&gt;
 *                   &lt;element ref="{}descr"/&gt;
 *                   &lt;choice&gt;
 *                     &lt;sequence&gt;
 *                       &lt;element ref="{}updated"/&gt;
 *                       &lt;sequence minOccurs="0"&gt;
 *                         &lt;element ref="{}created"/&gt;
 *                         &lt;element ref="{}disabled" minOccurs="0"/&gt;
 *                       &lt;/sequence&gt;
 *                     &lt;/sequence&gt;
 *                     &lt;sequence&gt;
 *                       &lt;element ref="{}gateway"/&gt;
 *                       &lt;element ref="{}created"/&gt;
 *                       &lt;element ref="{}updated"/&gt;
 *                       &lt;element ref="{}disabled"/&gt;
 *                     &lt;/sequence&gt;
 *                     &lt;sequence&gt;
 *                       &lt;element ref="{}created"/&gt;
 *                       &lt;element ref="{}updated"/&gt;
 *                       &lt;element ref="{}disabled" minOccurs="0"/&gt;
 *                     &lt;/sequence&gt;
 *                   &lt;/choice&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{}protocol"/&gt;
 *                   &lt;element ref="{}source"/&gt;
 *                   &lt;element ref="{}destination"/&gt;
 *                   &lt;element ref="{}descr"/&gt;
 *                   &lt;choice&gt;
 *                     &lt;sequence&gt;
 *                       &lt;element ref="{}updated"/&gt;
 *                       &lt;element ref="{}created"/&gt;
 *                     &lt;/sequence&gt;
 *                     &lt;sequence&gt;
 *                       &lt;element ref="{}created"/&gt;
 *                       &lt;element ref="{}updated"/&gt;
 *                     &lt;/sequence&gt;
 *                   &lt;/choice&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/choice&gt;
 *             &lt;/sequence&gt;
 *             &lt;sequence&gt;
 *               &lt;element ref="{}direction"/&gt;
 *               &lt;element ref="{}floating"/&gt;
 *               &lt;element ref="{}max"/&gt;
 *               &lt;element ref="{}max-src-nodes"/&gt;
 *               &lt;element ref="{}max-src-conn"/&gt;
 *               &lt;element ref="{}max-src-states"/&gt;
 *               &lt;element ref="{}statetimeout"/&gt;
 *               &lt;element ref="{}statetype"/&gt;
 *               &lt;element ref="{}os"/&gt;
 *               &lt;choice&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{}source"/&gt;
 *                   &lt;element ref="{}destination"/&gt;
 *                   &lt;element ref="{}descr"/&gt;
 *                   &lt;element ref="{}defaultqueue"/&gt;
 *                   &lt;element ref="{}created"/&gt;
 *                   &lt;element ref="{}updated"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{}protocol"/&gt;
 *                   &lt;element ref="{}source"/&gt;
 *                   &lt;element ref="{}destination"/&gt;
 *                   &lt;element ref="{}descr"/&gt;
 *                   &lt;element ref="{}defaultqueue"/&gt;
 *                   &lt;element ref="{}created"/&gt;
 *                   &lt;element ref="{}updated"/&gt;
 *                   &lt;element ref="{}disabled" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/choice&gt;
 *             &lt;/sequence&gt;
 *           &lt;/choice&gt;
 *         &lt;/sequence&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "rule")
public class Rule {

    @XmlElementRefs({
        @XmlElementRef(name = "type", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ipprotocol", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "descr", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "interface", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tracker", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "source", type = Source.class, required = false),
        @XmlElementRef(name = "destination", type = Destination.class, required = false),
        @XmlElementRef(name = "defaultqueue", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "floating", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wizard", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "enabled", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "protocol", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "created", type = Created.class, required = false),
        @XmlElementRef(name = "disabled", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sourceport", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "target", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "target_subnet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "poolopts", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "source_hash_key", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "staticnatport", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dstport", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "updated", type = Updated.class, required = false),
        @XmlElementRef(name = "log", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "natport", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "id", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tag", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tagged", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "max", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "max-src-nodes", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "max-src-conn", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "max-src-states", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "statetimeout", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "statetype", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "os", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "gateway", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "direction", type = JAXBElement.class, required = false)
    })
    protected List<Object> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Interface" is used by two different parts of a schema. See: 
     * line 795 of file:/opt/workspace/java-tools/pfsense/src/main/dtd/pfsense.xsd
     * line 789 of file:/opt/workspace/java-tools/pfsense/src/main/dtd/pfsense.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Created }
     * {@link Destination }
     * {@link Source }
     * {@link Updated }
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Short }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
