//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.12 at 10:13:53 PM EEST 
//


package eu.ad4ubg;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}protocol"/&gt;
 *         &lt;element ref="{}loginautocomplete"/&gt;
 *         &lt;element ref="{}ssl-certref"/&gt;
 *         &lt;element ref="{}dashboardcolumns"/&gt;
 *         &lt;element ref="{}webguicss"/&gt;
 *         &lt;element ref="{}logincss"/&gt;
 *         &lt;element ref="{}max_procs"/&gt;
 *         &lt;element ref="{}roaming"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "protocol",
    "loginautocomplete",
    "sslCertref",
    "dashboardcolumns",
    "webguicss",
    "logincss",
    "maxProcs",
    "roaming"
})
@XmlRootElement(name = "webgui")
public class Webgui {

    @XmlElement(required = true)
    protected String protocol;
    @XmlElement(required = true)
    protected String loginautocomplete;
    @XmlElement(name = "ssl-certref", required = true)
    protected String sslCertref;
    protected byte dashboardcolumns;
    @XmlElement(required = true)
    protected String webguicss;
    @XmlElement(required = true)
    protected String logincss;
    @XmlElement(name = "max_procs")
    protected byte maxProcs;
    @XmlElement(required = true)
    protected String roaming;

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol(String value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the loginautocomplete property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginautocomplete() {
        return loginautocomplete;
    }

    /**
     * Sets the value of the loginautocomplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginautocomplete(String value) {
        this.loginautocomplete = value;
    }

    /**
     * Gets the value of the sslCertref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSslCertref() {
        return sslCertref;
    }

    /**
     * Sets the value of the sslCertref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSslCertref(String value) {
        this.sslCertref = value;
    }

    /**
     * Gets the value of the dashboardcolumns property.
     * 
     */
    public byte getDashboardcolumns() {
        return dashboardcolumns;
    }

    /**
     * Sets the value of the dashboardcolumns property.
     * 
     */
    public void setDashboardcolumns(byte value) {
        this.dashboardcolumns = value;
    }

    /**
     * Gets the value of the webguicss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebguicss() {
        return webguicss;
    }

    /**
     * Sets the value of the webguicss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebguicss(String value) {
        this.webguicss = value;
    }

    /**
     * Gets the value of the logincss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogincss() {
        return logincss;
    }

    /**
     * Sets the value of the logincss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogincss(String value) {
        this.logincss = value;
    }

    /**
     * Gets the value of the maxProcs property.
     * 
     */
    public byte getMaxProcs() {
        return maxProcs;
    }

    /**
     * Sets the value of the maxProcs property.
     * 
     */
    public void setMaxProcs(byte value) {
        this.maxProcs = value;
    }

    /**
     * Gets the value of the roaming property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoaming() {
        return roaming;
    }

    /**
     * Sets the value of the roaming property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoaming(String value) {
        this.roaming = value;
    }

}
