tv-proxy.username=atan
tv-proxy.password=1234
tv-proxy.host=151.237.24.6
tv-proxy.port=4000
tv-proxy.channel.list.url=http://${tv-proxy.host}:${tv-proxy.port}/player_api.php?username=${tv-proxy.username}&password=${tv-proxy.password}&action=get_live_streams
tv-proxy.category.list.url=http://${tv-proxy.host}:${tv-proxy.port}/player_api.php?username=${tv-proxy.username}&password=${tv-proxy.password}&action=get_live_categories
#quarkus.package.jar.type=uber-jar
quarkus.http.host=0.0.0.0