# Настройки за лог файла на Quarkus
quarkus.log.file.enable=true
quarkus.log.file.path=emby_automation.log
quarkus.log.file.level=INFO
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n

# Настройки за REST клиентите
quarkus.rest-client.tvdb-api.url=https://api.thetvdb.com
quarkus.rest-client.emby-api.url=http://nas.ad4u-bg.com:46231
quarkus.rest-client.tvmaze-api.url=https://api.tvmaze.com

#quarkus.rest-client.logging.scope=request-response
#quarkus.rest-client.logging.body-limit=5000
#quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG