//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.30 at 04:44:02 AM EET 
//


package net.ifao.aida;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Tickets" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}FlightBaggage" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}FlightSeat" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}FlightMeal" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}GeoLocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}CarbonEmission" minOccurs="0"/&gt;
 *         &lt;element ref="{}AirlineLogos" minOccurs="0"/&gt;
 *         &lt;element ref="{}OperatedByAirlineLogos" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{}Integer" /&gt;
 *       &lt;attribute name="direction" type="{}Integer" /&gt;
 *       &lt;attribute name="airlineCode" type="{}String" /&gt;
 *       &lt;attribute name="airline" type="{}String" /&gt;
 *       &lt;attribute name="operatedByAirlineCode" type="{}String" /&gt;
 *       &lt;attribute name="operatedByAirline" type="{}String" /&gt;
 *       &lt;attribute name="inventoryCode" type="{}String" /&gt;
 *       &lt;attribute name="origin" type="{}String" /&gt;
 *       &lt;attribute name="destination" type="{}String" /&gt;
 *       &lt;attribute name="originTerminal" type="{}String" /&gt;
 *       &lt;attribute name="destinationTerminal" type="{}String" /&gt;
 *       &lt;attribute name="originDateAndTime" type="{}DateTime" /&gt;
 *       &lt;attribute name="destinationDateAndTime" type="{}DateTime" /&gt;
 *       &lt;attribute name="originCityCode" type="{}String" /&gt;
 *       &lt;attribute name="originCity" type="{}String" /&gt;
 *       &lt;attribute name="destinationCityCode" type="{}String" /&gt;
 *       &lt;attribute name="destinationCity" type="{}String" /&gt;
 *       &lt;attribute name="originCountryCode" type="{}String" /&gt;
 *       &lt;attribute name="originCountry" type="{}String" /&gt;
 *       &lt;attribute name="destinationCountryCode" type="{}String" /&gt;
 *       &lt;attribute name="destinationCountry" type="{}String" /&gt;
 *       &lt;attribute name="originIATACode" type="{}String" /&gt;
 *       &lt;attribute name="destinationIATACode" type="{}String" /&gt;
 *       &lt;attribute name="originArea" type="{}EnumArea" /&gt;
 *       &lt;attribute name="destinationArea" type="{}EnumArea" /&gt;
 *       &lt;attribute name="bookingClass" type="{}EnumBookingClass" /&gt;
 *       &lt;attribute name="serviceClass" type="{}EnumAirServiceClass" /&gt;
 *       &lt;attribute name="providerConfirmationNumber" type="{}String" /&gt;
 *       &lt;attribute name="fareBasis" type="{}String" /&gt;
 *       &lt;attribute name="equipment" type="{}String" /&gt;
 *       &lt;attribute name="codeShared" type="{}Boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tickets",
    "flightBaggage",
    "flightSeat",
    "flightMeal",
    "geoLocation",
    "carbonEmission",
    "airlineLogos",
    "operatedByAirlineLogos"
})
@XmlRootElement(name = "AirSubsegment")
public class AirSubsegment {

    @XmlElement(name = "Tickets")
    protected List<Tickets> tickets;
    @XmlElement(name = "FlightBaggage")
    protected List<FlightBaggage> flightBaggage;
    @XmlElement(name = "FlightSeat")
    protected List<FlightSeat> flightSeat;
    @XmlElement(name = "FlightMeal")
    protected List<FlightMeal> flightMeal;
    @XmlElement(name = "GeoLocation")
    protected List<GeoLocation> geoLocation;
    @XmlElement(name = "CarbonEmission")
    protected CarbonEmission carbonEmission;
    @XmlElement(name = "AirlineLogos")
    protected AirlineLogos airlineLogos;
    @XmlElement(name = "OperatedByAirlineLogos")
    protected OperatedByAirlineLogos operatedByAirlineLogos;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "direction")
    protected String direction;
    @XmlAttribute(name = "airlineCode")
    protected String airlineCode;
    @XmlAttribute(name = "airline")
    protected String airline;
    @XmlAttribute(name = "operatedByAirlineCode")
    protected String operatedByAirlineCode;
    @XmlAttribute(name = "operatedByAirline")
    protected String operatedByAirline;
    @XmlAttribute(name = "inventoryCode")
    protected String inventoryCode;
    @XmlAttribute(name = "origin")
    protected String origin;
    @XmlAttribute(name = "destination")
    protected String destination;
    @XmlAttribute(name = "originTerminal")
    protected String originTerminal;
    @XmlAttribute(name = "destinationTerminal")
    protected String destinationTerminal;
    @XmlAttribute(name = "originDateAndTime")
    protected String originDateAndTime;
    @XmlAttribute(name = "destinationDateAndTime")
    protected String destinationDateAndTime;
    @XmlAttribute(name = "originCityCode")
    protected String originCityCode;
    @XmlAttribute(name = "originCity")
    protected String originCity;
    @XmlAttribute(name = "destinationCityCode")
    protected String destinationCityCode;
    @XmlAttribute(name = "destinationCity")
    protected String destinationCity;
    @XmlAttribute(name = "originCountryCode")
    protected String originCountryCode;
    @XmlAttribute(name = "originCountry")
    protected String originCountry;
    @XmlAttribute(name = "destinationCountryCode")
    protected String destinationCountryCode;
    @XmlAttribute(name = "destinationCountry")
    protected String destinationCountry;
    @XmlAttribute(name = "originIATACode")
    protected String originIATACode;
    @XmlAttribute(name = "destinationIATACode")
    protected String destinationIATACode;
    @XmlAttribute(name = "originArea")
    protected EnumArea originArea;
    @XmlAttribute(name = "destinationArea")
    protected EnumArea destinationArea;
    @XmlAttribute(name = "bookingClass")
    protected EnumBookingClass bookingClass;
    @XmlAttribute(name = "serviceClass")
    protected EnumAirServiceClass serviceClass;
    @XmlAttribute(name = "providerConfirmationNumber")
    protected String providerConfirmationNumber;
    @XmlAttribute(name = "fareBasis")
    protected String fareBasis;
    @XmlAttribute(name = "equipment")
    protected String equipment;
    @XmlAttribute(name = "codeShared")
    protected String codeShared;

    /**
     * Gets the value of the tickets property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the tickets property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTickets().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tickets }
     * 
     * 
     */
    public List<Tickets> getTickets() {
        if (tickets == null) {
            tickets = new ArrayList<Tickets>();
        }
        return this.tickets;
    }

    /**
     * Gets the value of the flightBaggage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the flightBaggage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlightBaggage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightBaggage }
     * 
     * 
     */
    public List<FlightBaggage> getFlightBaggage() {
        if (flightBaggage == null) {
            flightBaggage = new ArrayList<FlightBaggage>();
        }
        return this.flightBaggage;
    }

    /**
     * Gets the value of the flightSeat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the flightSeat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlightSeat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightSeat }
     * 
     * 
     */
    public List<FlightSeat> getFlightSeat() {
        if (flightSeat == null) {
            flightSeat = new ArrayList<FlightSeat>();
        }
        return this.flightSeat;
    }

    /**
     * Gets the value of the flightMeal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the flightMeal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlightMeal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightMeal }
     * 
     * 
     */
    public List<FlightMeal> getFlightMeal() {
        if (flightMeal == null) {
            flightMeal = new ArrayList<FlightMeal>();
        }
        return this.flightMeal;
    }

    /**
     * Gets the value of the geoLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the geoLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeoLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeoLocation }
     * 
     * 
     */
    public List<GeoLocation> getGeoLocation() {
        if (geoLocation == null) {
            geoLocation = new ArrayList<GeoLocation>();
        }
        return this.geoLocation;
    }

    /**
     * Gets the value of the carbonEmission property.
     * 
     * @return
     *     possible object is
     *     {@link CarbonEmission }
     *     
     */
    public CarbonEmission getCarbonEmission() {
        return carbonEmission;
    }

    /**
     * Sets the value of the carbonEmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarbonEmission }
     *     
     */
    public void setCarbonEmission(CarbonEmission value) {
        this.carbonEmission = value;
    }

    /**
     * Gets the value of the airlineLogos property.
     * 
     * @return
     *     possible object is
     *     {@link AirlineLogos }
     *     
     */
    public AirlineLogos getAirlineLogos() {
        return airlineLogos;
    }

    /**
     * Sets the value of the airlineLogos property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirlineLogos }
     *     
     */
    public void setAirlineLogos(AirlineLogos value) {
        this.airlineLogos = value;
    }

    /**
     * Gets the value of the operatedByAirlineLogos property.
     * 
     * @return
     *     possible object is
     *     {@link OperatedByAirlineLogos }
     *     
     */
    public OperatedByAirlineLogos getOperatedByAirlineLogos() {
        return operatedByAirlineLogos;
    }

    /**
     * Sets the value of the operatedByAirlineLogos property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatedByAirlineLogos }
     *     
     */
    public void setOperatedByAirlineLogos(OperatedByAirlineLogos value) {
        this.operatedByAirlineLogos = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the airlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirlineCode() {
        return airlineCode;
    }

    /**
     * Sets the value of the airlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirlineCode(String value) {
        this.airlineCode = value;
    }

    /**
     * Gets the value of the airline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirline() {
        return airline;
    }

    /**
     * Sets the value of the airline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirline(String value) {
        this.airline = value;
    }

    /**
     * Gets the value of the operatedByAirlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatedByAirlineCode() {
        return operatedByAirlineCode;
    }

    /**
     * Sets the value of the operatedByAirlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatedByAirlineCode(String value) {
        this.operatedByAirlineCode = value;
    }

    /**
     * Gets the value of the operatedByAirline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatedByAirline() {
        return operatedByAirline;
    }

    /**
     * Sets the value of the operatedByAirline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatedByAirline(String value) {
        this.operatedByAirline = value;
    }

    /**
     * Gets the value of the inventoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryCode() {
        return inventoryCode;
    }

    /**
     * Sets the value of the inventoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryCode(String value) {
        this.inventoryCode = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the originTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginTerminal() {
        return originTerminal;
    }

    /**
     * Sets the value of the originTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginTerminal(String value) {
        this.originTerminal = value;
    }

    /**
     * Gets the value of the destinationTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationTerminal() {
        return destinationTerminal;
    }

    /**
     * Sets the value of the destinationTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationTerminal(String value) {
        this.destinationTerminal = value;
    }

    /**
     * Gets the value of the originDateAndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginDateAndTime() {
        return originDateAndTime;
    }

    /**
     * Sets the value of the originDateAndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginDateAndTime(String value) {
        this.originDateAndTime = value;
    }

    /**
     * Gets the value of the destinationDateAndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationDateAndTime() {
        return destinationDateAndTime;
    }

    /**
     * Sets the value of the destinationDateAndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationDateAndTime(String value) {
        this.destinationDateAndTime = value;
    }

    /**
     * Gets the value of the originCityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginCityCode() {
        return originCityCode;
    }

    /**
     * Sets the value of the originCityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginCityCode(String value) {
        this.originCityCode = value;
    }

    /**
     * Gets the value of the originCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginCity() {
        return originCity;
    }

    /**
     * Sets the value of the originCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginCity(String value) {
        this.originCity = value;
    }

    /**
     * Gets the value of the destinationCityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationCityCode() {
        return destinationCityCode;
    }

    /**
     * Sets the value of the destinationCityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationCityCode(String value) {
        this.destinationCityCode = value;
    }

    /**
     * Gets the value of the destinationCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationCity() {
        return destinationCity;
    }

    /**
     * Sets the value of the destinationCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationCity(String value) {
        this.destinationCity = value;
    }

    /**
     * Gets the value of the originCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginCountryCode() {
        return originCountryCode;
    }

    /**
     * Sets the value of the originCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginCountryCode(String value) {
        this.originCountryCode = value;
    }

    /**
     * Gets the value of the originCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginCountry() {
        return originCountry;
    }

    /**
     * Sets the value of the originCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginCountry(String value) {
        this.originCountry = value;
    }

    /**
     * Gets the value of the destinationCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationCountryCode() {
        return destinationCountryCode;
    }

    /**
     * Sets the value of the destinationCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationCountryCode(String value) {
        this.destinationCountryCode = value;
    }

    /**
     * Gets the value of the destinationCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationCountry() {
        return destinationCountry;
    }

    /**
     * Sets the value of the destinationCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationCountry(String value) {
        this.destinationCountry = value;
    }

    /**
     * Gets the value of the originIATACode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginIATACode() {
        return originIATACode;
    }

    /**
     * Sets the value of the originIATACode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginIATACode(String value) {
        this.originIATACode = value;
    }

    /**
     * Gets the value of the destinationIATACode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationIATACode() {
        return destinationIATACode;
    }

    /**
     * Sets the value of the destinationIATACode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationIATACode(String value) {
        this.destinationIATACode = value;
    }

    /**
     * Gets the value of the originArea property.
     * 
     * @return
     *     possible object is
     *     {@link EnumArea }
     *     
     */
    public EnumArea getOriginArea() {
        return originArea;
    }

    /**
     * Sets the value of the originArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumArea }
     *     
     */
    public void setOriginArea(EnumArea value) {
        this.originArea = value;
    }

    /**
     * Gets the value of the destinationArea property.
     * 
     * @return
     *     possible object is
     *     {@link EnumArea }
     *     
     */
    public EnumArea getDestinationArea() {
        return destinationArea;
    }

    /**
     * Sets the value of the destinationArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumArea }
     *     
     */
    public void setDestinationArea(EnumArea value) {
        this.destinationArea = value;
    }

    /**
     * Gets the value of the bookingClass property.
     * 
     * @return
     *     possible object is
     *     {@link EnumBookingClass }
     *     
     */
    public EnumBookingClass getBookingClass() {
        return bookingClass;
    }

    /**
     * Sets the value of the bookingClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumBookingClass }
     *     
     */
    public void setBookingClass(EnumBookingClass value) {
        this.bookingClass = value;
    }

    /**
     * Gets the value of the serviceClass property.
     * 
     * @return
     *     possible object is
     *     {@link EnumAirServiceClass }
     *     
     */
    public EnumAirServiceClass getServiceClass() {
        return serviceClass;
    }

    /**
     * Sets the value of the serviceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumAirServiceClass }
     *     
     */
    public void setServiceClass(EnumAirServiceClass value) {
        this.serviceClass = value;
    }

    /**
     * Gets the value of the providerConfirmationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderConfirmationNumber() {
        return providerConfirmationNumber;
    }

    /**
     * Sets the value of the providerConfirmationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderConfirmationNumber(String value) {
        this.providerConfirmationNumber = value;
    }

    /**
     * Gets the value of the fareBasis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareBasis() {
        return fareBasis;
    }

    /**
     * Sets the value of the fareBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareBasis(String value) {
        this.fareBasis = value;
    }

    /**
     * Gets the value of the equipment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipment() {
        return equipment;
    }

    /**
     * Sets the value of the equipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipment(String value) {
        this.equipment = value;
    }

    /**
     * Gets the value of the codeShared property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeShared() {
        return codeShared;
    }

    /**
     * Sets the value of the codeShared property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeShared(String value) {
        this.codeShared = value;
    }

}
