//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.30 at 04:44:02 AM EET 
//


package net.ifao.aida;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnumPassiveSystem.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="EnumPassiveSystem"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="AMADEUS"/&gt;
 *     &lt;enumeration value="GALILEO"/&gt;
 *     &lt;enumeration value="SABRE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EnumPassiveSystem")
@XmlEnum
public enum EnumPassiveSystem {

    AMADEUS,
    GALILEO,
    SABRE;

    public String value() {
        return name();
    }

    public static EnumPassiveSystem fromValue(String v) {
        return valueOf(v);
    }

}
