//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.30 at 04:44:02 AM EET 
//


package net.ifao.aida;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnumCarCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="EnumCarCategory"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="C"/&gt;
 *     &lt;enumeration value="E"/&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="I"/&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="M"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="S"/&gt;
 *     &lt;enumeration value="X"/&gt;
 *     &lt;enumeration value="N"/&gt;
 *     &lt;enumeration value="H"/&gt;
 *     &lt;enumeration value="D"/&gt;
 *     &lt;enumeration value="J"/&gt;
 *     &lt;enumeration value="R"/&gt;
 *     &lt;enumeration value="G"/&gt;
 *     &lt;enumeration value="U"/&gt;
 *     &lt;enumeration value="W"/&gt;
 *     &lt;enumeration value="O"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EnumCarCategory")
@XmlEnum
public enum EnumCarCategory {

    C,
    E,
    F,
    I,
    L,
    M,
    P,
    S,
    X,
    N,
    H,
    D,
    J,
    R,
    G,
    U,
    W,
    O;

    public String value() {
        return name();
    }

    public static EnumCarCategory fromValue(String v) {
        return valueOf(v);
    }

}
