//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.30 at 04:44:02 AM EET 
//


package net.ifao.aida;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="reasonCode" type="{}String" /&gt;
 *       &lt;attribute name="explanation" type="{}String" /&gt;
 *       &lt;attribute name="reasonCodeComment" type="{}String" /&gt;
 *       &lt;attribute name="advanceReasonCode" type="{}String" /&gt;
 *       &lt;attribute name="noHotelReasonCode" type="{}String" /&gt;
 *       &lt;attribute name="noHotelExplanation" type="{}String" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "TravelPolicyAlert")
public class TravelPolicyAlert {

    @XmlAttribute(name = "reasonCode")
    protected String reasonCode;
    @XmlAttribute(name = "explanation")
    protected String explanation;
    @XmlAttribute(name = "reasonCodeComment")
    protected String reasonCodeComment;
    @XmlAttribute(name = "advanceReasonCode")
    protected String advanceReasonCode;
    @XmlAttribute(name = "noHotelReasonCode")
    protected String noHotelReasonCode;
    @XmlAttribute(name = "noHotelExplanation")
    protected String noHotelExplanation;

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the explanation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExplanation() {
        return explanation;
    }

    /**
     * Sets the value of the explanation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExplanation(String value) {
        this.explanation = value;
    }

    /**
     * Gets the value of the reasonCodeComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCodeComment() {
        return reasonCodeComment;
    }

    /**
     * Sets the value of the reasonCodeComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCodeComment(String value) {
        this.reasonCodeComment = value;
    }

    /**
     * Gets the value of the advanceReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvanceReasonCode() {
        return advanceReasonCode;
    }

    /**
     * Sets the value of the advanceReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvanceReasonCode(String value) {
        this.advanceReasonCode = value;
    }

    /**
     * Gets the value of the noHotelReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoHotelReasonCode() {
        return noHotelReasonCode;
    }

    /**
     * Sets the value of the noHotelReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoHotelReasonCode(String value) {
        this.noHotelReasonCode = value;
    }

    /**
     * Gets the value of the noHotelExplanation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoHotelExplanation() {
        return noHotelExplanation;
    }

    /**
     * Sets the value of the noHotelExplanation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoHotelExplanation(String value) {
        this.noHotelExplanation = value;
    }

}
