//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.30 at 04:44:02 AM EET 
//


package net.ifao.aida;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}HotelRate" minOccurs="0"/&gt;
 *         &lt;element ref="{}GeoLocation" minOccurs="0"/&gt;
 *         &lt;element ref="{}Image" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}ChainLogos" minOccurs="0"/&gt;
 *         &lt;element ref="{}ProviderLogos" minOccurs="0"/&gt;
 *         &lt;element ref="{}LowestFares" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="inventoryCode" type="{}String" /&gt;
 *       &lt;attribute name="name" type="{}String" /&gt;
 *       &lt;attribute name="street" type="{}String" /&gt;
 *       &lt;attribute name="city" type="{}String" /&gt;
 *       &lt;attribute name="country" type="{}String" /&gt;
 *       &lt;attribute name="telephone" type="{}String" /&gt;
 *       &lt;attribute name="hotelChain" type="{}String" /&gt;
 *       &lt;attribute name="breakfastIncluded" use="required" type="{}Tristate" /&gt;
 *       &lt;attribute name="roomOccupancy" use="required" type="{}Integer" /&gt;
 *       &lt;attribute name="providerConfirmationNumber" type="{}String" /&gt;
 *       &lt;attribute name="stars" type="{}Integer" /&gt;
 *       &lt;attribute name="cancellationPolicy" type="{}String" /&gt;
 *       &lt;attribute name="preferred" type="{}Boolean" /&gt;
 *       &lt;attribute name="isPartOfProgram" type="{}Boolean" /&gt;
 *       &lt;attribute name="statusCode" type="{}String" /&gt;
 *       &lt;attribute name="planCode" type="{}String" /&gt;
 *       &lt;attribute name="roomCode" type="{}String" /&gt;
 *       &lt;attribute name="fax" type="{}String" /&gt;
 *       &lt;attribute name="postalcode" type="{}String" /&gt;
 *       &lt;attribute name="email" type="{}String" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hotelRate",
    "geoLocation",
    "image",
    "chainLogos",
    "providerLogos",
    "lowestFares"
})
@XmlRootElement(name = "TripDetailsHotel")
public class TripDetailsHotel {

    @XmlElement(name = "HotelRate")
    protected HotelRate hotelRate;
    @XmlElement(name = "GeoLocation")
    protected GeoLocation geoLocation;
    @XmlElement(name = "Image")
    protected List<Image> image;
    @XmlElement(name = "ChainLogos")
    protected ChainLogos chainLogos;
    @XmlElement(name = "ProviderLogos")
    protected ProviderLogos providerLogos;
    @XmlElement(name = "LowestFares")
    protected LowestFares lowestFares;
    @XmlAttribute(name = "inventoryCode")
    protected String inventoryCode;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "street")
    protected String street;
    @XmlAttribute(name = "city")
    protected String city;
    @XmlAttribute(name = "country")
    protected String country;
    @XmlAttribute(name = "telephone")
    protected String telephone;
    @XmlAttribute(name = "hotelChain")
    protected String hotelChain;
    @XmlAttribute(name = "breakfastIncluded", required = true)
    protected String breakfastIncluded;
    @XmlAttribute(name = "roomOccupancy", required = true)
    protected String roomOccupancy;
    @XmlAttribute(name = "providerConfirmationNumber")
    protected String providerConfirmationNumber;
    @XmlAttribute(name = "stars")
    protected String stars;
    @XmlAttribute(name = "cancellationPolicy")
    protected String cancellationPolicy;
    @XmlAttribute(name = "preferred")
    protected String preferred;
    @XmlAttribute(name = "isPartOfProgram")
    protected String isPartOfProgram;
    @XmlAttribute(name = "statusCode")
    protected String statusCode;
    @XmlAttribute(name = "planCode")
    protected String planCode;
    @XmlAttribute(name = "roomCode")
    protected String roomCode;
    @XmlAttribute(name = "fax")
    protected String fax;
    @XmlAttribute(name = "postalcode")
    protected String postalcode;
    @XmlAttribute(name = "email")
    protected String email;

    /**
     * Gets the value of the hotelRate property.
     * 
     * @return
     *     possible object is
     *     {@link HotelRate }
     *     
     */
    public HotelRate getHotelRate() {
        return hotelRate;
    }

    /**
     * Sets the value of the hotelRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelRate }
     *     
     */
    public void setHotelRate(HotelRate value) {
        this.hotelRate = value;
    }

    /**
     * Gets the value of the geoLocation property.
     * 
     * @return
     *     possible object is
     *     {@link GeoLocation }
     *     
     */
    public GeoLocation getGeoLocation() {
        return geoLocation;
    }

    /**
     * Sets the value of the geoLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoLocation }
     *     
     */
    public void setGeoLocation(GeoLocation value) {
        this.geoLocation = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the image property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Image }
     * 
     * 
     */
    public List<Image> getImage() {
        if (image == null) {
            image = new ArrayList<Image>();
        }
        return this.image;
    }

    /**
     * Gets the value of the chainLogos property.
     * 
     * @return
     *     possible object is
     *     {@link ChainLogos }
     *     
     */
    public ChainLogos getChainLogos() {
        return chainLogos;
    }

    /**
     * Sets the value of the chainLogos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChainLogos }
     *     
     */
    public void setChainLogos(ChainLogos value) {
        this.chainLogos = value;
    }

    /**
     * Gets the value of the providerLogos property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderLogos }
     *     
     */
    public ProviderLogos getProviderLogos() {
        return providerLogos;
    }

    /**
     * Sets the value of the providerLogos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderLogos }
     *     
     */
    public void setProviderLogos(ProviderLogos value) {
        this.providerLogos = value;
    }

    /**
     * Gets the value of the lowestFares property.
     * 
     * @return
     *     possible object is
     *     {@link LowestFares }
     *     
     */
    public LowestFares getLowestFares() {
        return lowestFares;
    }

    /**
     * Sets the value of the lowestFares property.
     * 
     * @param value
     *     allowed object is
     *     {@link LowestFares }
     *     
     */
    public void setLowestFares(LowestFares value) {
        this.lowestFares = value;
    }

    /**
     * Gets the value of the inventoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryCode() {
        return inventoryCode;
    }

    /**
     * Sets the value of the inventoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryCode(String value) {
        this.inventoryCode = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the telephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * Sets the value of the telephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephone(String value) {
        this.telephone = value;
    }

    /**
     * Gets the value of the hotelChain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHotelChain() {
        return hotelChain;
    }

    /**
     * Sets the value of the hotelChain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHotelChain(String value) {
        this.hotelChain = value;
    }

    /**
     * Gets the value of the breakfastIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreakfastIncluded() {
        return breakfastIncluded;
    }

    /**
     * Sets the value of the breakfastIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreakfastIncluded(String value) {
        this.breakfastIncluded = value;
    }

    /**
     * Gets the value of the roomOccupancy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomOccupancy() {
        return roomOccupancy;
    }

    /**
     * Sets the value of the roomOccupancy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomOccupancy(String value) {
        this.roomOccupancy = value;
    }

    /**
     * Gets the value of the providerConfirmationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderConfirmationNumber() {
        return providerConfirmationNumber;
    }

    /**
     * Sets the value of the providerConfirmationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderConfirmationNumber(String value) {
        this.providerConfirmationNumber = value;
    }

    /**
     * Gets the value of the stars property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStars() {
        return stars;
    }

    /**
     * Sets the value of the stars property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStars(String value) {
        this.stars = value;
    }

    /**
     * Gets the value of the cancellationPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellationPolicy() {
        return cancellationPolicy;
    }

    /**
     * Sets the value of the cancellationPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationPolicy(String value) {
        this.cancellationPolicy = value;
    }

    /**
     * Gets the value of the preferred property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferred() {
        return preferred;
    }

    /**
     * Sets the value of the preferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferred(String value) {
        this.preferred = value;
    }

    /**
     * Gets the value of the isPartOfProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPartOfProgram() {
        return isPartOfProgram;
    }

    /**
     * Sets the value of the isPartOfProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPartOfProgram(String value) {
        this.isPartOfProgram = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the planCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanCode() {
        return planCode;
    }

    /**
     * Sets the value of the planCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanCode(String value) {
        this.planCode = value;
    }

    /**
     * Gets the value of the roomCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomCode() {
        return roomCode;
    }

    /**
     * Sets the value of the roomCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomCode(String value) {
        this.roomCode = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the postalcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * Sets the value of the postalcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalcode(String value) {
        this.postalcode = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

}
